### ISSUE TITLE
Ranged characters tend to move ahead / to the side and aggroing mobs

### ISSUE THREAD

**Issue by Corgicorgicorgi** [trickerer/Trinity-Bots#156]
Hello,

I have a hunter and a priest in my team and every time I engage an enemy, they tend to move ahead or to the side of the pack (about 20 yards) and as a result aggroing more mobs.

I have tried setting the follow distance and attack distance but no luck.

I used to play an older version of TC and bots that was included in [this repack](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-emulator-servers/wow-emu-general-releases/904235-trinitycore-npcbots-repack-update-25-06-2020-a.html) and this was not a problem. Three days ago I decided to compile my own and pulled latest, and it is now exhibiting this behaviour.

Thanks!

**Comment by TQPS** [comment]
I have noticed this too.

Got some examples.

Firstly: 39 Bots, we're all level 60, most decently MC geared, couple of pieces from Azuregos
Multiplier damage is on 0.2 

Bots Moving forward: Molten Core: Baron Geddon

This boss is the only 1 we cant take down and I'm almost exalted with Hydraxian (we do the other 7)

All bots that are ranged are set to attack ranged but for some reason, whenever we engage the Baron everyone runs forward a little and as a result I lose 3/4 of the raid to the first or definitely second Inferno. Not sure why but even ranged appear to always fight too close. They dont run from Inferno either so they all get cooked. Note: Ranged have been set to "Ranged" via their individual bot menus.

I have noticed on occassion, it can take the bots a few moments to realise we've engaged him. Then suddenly, they'll move in (even ranged) and attack.

Bots Moving to the side: Molten Core: Shazzrah

As above, we cant do Geddon so we have to avoid him (taking at least 1 wipe to soulstone rez past his pathing)

When it comes to Shazzrah, we need to engage him on the very southern tip of the bank right next to the lava so as to not pull Geddon in. All bots, except tank, stand close to me (some in the lava) but when I pull him, some bots, definitely a healer or two, flare out to the sides and as a result, more than 50% of the time, they pull Geddon into the fight.

I've learnt to accommodate this playstyle but since it's been brought up, I thought I'd share what I'm experiencing.

**Comment by trickerer** [comment]
Yes, bot do try to position themselves in the back or on the side of the target (except PvP situations), but only if player is in melee distance to target or behind it too.
They do that to avoid possible frontal aoe attacks, cannot predict posibility of such attacks just by checking the target, and to follow player's ranged positioning pattern.
Problems are possible if player tanks while ranged bots need to stand considerable distance away from target (like Geddon). Possible solution is to make bots tank.
If bots go too far you can just reduce `.npcbot attack distance`. The distance is calculated from target's exact position so attack distance 1 makes bots stand pretty much on top of the target regardless

So, if you melee - set attack distance somewhat low, if ranged and bots already went behind the target when you were close to it just briefly - step back until bots decice they are too far away from you and position themselves on your side. And you need to keep attacking the target creature, or set follow distance pretty high to not break melee bots' attack.

**Comment by Mr-Deadbeat** [comment]
the way i usually engage packs of mobs or if i tank is i pull the groups way back to nullify the chance they might aggro more mobs to the fight although depends on how well equipped your bots and you are and how much of a beating you can sustain

some fights you just have to adapt and overcome for example Pit of Saron on heroic is a pain with bots unless you make sure their don't do anything while you run to the safe spot inside the cave just before the final boss crappy thing is sometimes the bot healer starts healing mid run and end up dead adds some spice to say the least ;) but it's doable

**Comment by Corgicorgicorgi** [comment]
Ah, thanks for the explanation, that logic makes sense. I'll adapt to this playstyle.
