### ISSUE TITLE
[Question] Command to tell bots to run away?

### ISSUE THREAD

**Issue by Corgicorgicorgi** [trickerer/Trinity-Bots#163]
Hello,

Just curious if there's such a command to tell bots to run away from the mob that they are attacking. Sometimes bosses like Ick in Pit of Saron and Sindragosa in ICC will cast an AOE centered around the boss with huge damage, and could be easily avoided if some distance is kept.

What do you do in these encounters? I've tried setting the follow distance `.npcbot distance 0` to force them to follow me and attack distance `.npcbot distance attack 30` mid-fight but they seem to just ignore it.

Thanks!

**Comment by trickerer** [comment]
Hi there.

There is no special command for this currently. I guess if I were to implement something like this it would be a command that makes all melee bots to be temporarily affected by ranged positioning rules. Idea is that they will instantly move away from their target and assume a safe position, moving farther away if needed.

As for existing commands: '.npcbot distance attack' only works for ranged bots and '.npcbot distance 0' makes bots follow you if and when you are not attacking anything.
The general idea currently is to set '.npcbot distance 0' and cancel attack when you need bots to run away from the target (except the tank maybe), and start attacking again when AoE phase is over. You may need a couple tries to get a feel for bots' reaction time to this. The problem is of course that this affects ranged bots while they could be continuing DPSing.

**Comment by Corgicorgicorgi** [comment]
Thanks for your answer. I didn't know I have to cancel attack as well. I made a macro
```
/cleartarget
.npcbot distance 0
```
and used it whenever that AOE is cast. Now instead of hitting pretty much all characters, it's hitting maybe just half of them. Not perfect but it's an improvement and it prolonged the fight a bit. Looking forward to the day where there's better support for this :)

Another unrelated question about AOE over time -- how is it determined whether it's an AOE or not? For some bosses, the bots are dodging the AOEs very well, but in some boss encounters like Grobbulus in Naxx or Acidmaw in ToC where there's green stuff growing on the ground, they just stand on top of it. Is it checked on a case-by-case basis or is there some universal rule to determine if it's an AOE?

**Comment by trickerer** [comment]
Both actually. Many abilities do work in the same way in terms of AoE sources. There are two general approaches used to find AoE zones, but additionally there are checks for special cases where AoE source is scripted and cannot be normally determined. Such checks currently exist for Eye of Eternity (Static Field) and Zul'Aman (Fire Bomb).

**Comment by Corgicorgicorgi** [comment]
Wonderful, thanks for your answer! Hope to see more and more AOE checks added someday.

Just to close the loop on the original issue, I further optimized the macro to
```
.npcbot command stopfully
.npcbot command follow
/cleartarget
.npcbot distance 0
```
so bots will immediately stop casting and follow me so they have more time to escape, and I was finally able to beat Sindragosa with this. In fact, using the same macro, I was able to beat Hodir in Ulduar where you have to walk into the ice circle before the AOE freeze happens.
