### ISSUE TITLE
Class Specific Bot mounts

### ISSUE THREAD

**Issue by thordarsen** [trickerer/Trinity-Bots#195]
I have updated my copy of your bots mod to have the class specific mounts for warlocks/paladins/death knights. You mentioned in this comment that the system used to have racial ones, before the current cloning of the player's mount. 
I know that not matching the mount type/speed might cause issues, but I think I have enough sanity checks where it reverts to the current behavior. Was there some other issue that I'm missing (conflict with the vehicle system)? 

I can submit it as a pull request if you want - I just didn't want to drop one out of nowhere on you, for a feature you might not want.

This should show my changes: https://github.com/thordarsen/TrinityCore-3.3.5-with-NPCBots/commit/b395ae537f8bf5a6b32ec06855a85120ff1fc19f

**Comment by trickerer** [comment]
The idea of diversifying bot mounts isn't bad, but leaving other classes unattended seems wrong. Full class/race mount selection algorithms seems more appropriate, but no worries, I'm not degrading your work.
Feel free to open a pull request, I'll point out a couple of problems I see in this code there.

---
If I remember correctly, previous system was trying to set mount display ID directly instead of using a spell, also there was a problem with finding a proper speed setting or something.

**Comment by thordarsen** [comment]
Yeah, I plan on adding the other racial mounts. I just had this part done first (because I happen to be using a DK/Pally with my 'lock - and I threw in Deathcharger's reins on the Dark Ranger cuz I was feeling saucy.)
And I'm sure there are issues in the code - I got it to "it works and at least kinda matches the coding style of the rest." Coding hasn't been my day job in a long while, and even then it was more scripting languages.

Ok, lets see if I can get the pull request right.

**Comment by thordarsen** [comment]
Welp. I was about to post that I had a patch to include race mounts, but I see you went ahead and did it better.

**Comment by thordarsen** [comment]
Pretty sure this can be closed now?

**Comment by trickerer** [comment]
Yeah, sure
