### ISSUE TITLE
Some observations running around at level 60

### ISSUE THREAD

**Issue by thordarsen** [trickerer/Trinity-Bots#198]
First, an appreciation: this thing is great. I could do all the dungeons fairly straightforwardly, even a DM Tribute run.

Second, it appears that druid bear forms are multiplying ring/trinket/weapon based armor (which was an early classic calculation, but quickly changed) not just the cloth/leather gear - but a quick look at the code, I'm not sure it's an easy fix, because the bots are "creatures" and not "players" - simple solution: don't equip that gear.

Third: I love the Dark Ranger, but is her damage output supposed to be... insane? 
Black Arrow's DoT ticks for 700 damage (100 base +10/level) before the sub 20% 5x multiplier kicks in (which is mostly overkill until you get to bosses, which just go from 20-> dead in a blink). Give her Agi gear and everything else skyrockets too. I had to manually update my version to drop the scaling so she didn't just solo everything. Like I get she's an Elite, but...

The bot's all seem to get a base 1/level resist all, is that intentional? (The elites get more, but I know that's intentional)

**Comment by trickerer** [comment]
1) Thanks. I occasionally check youtube for npcbots videos and there are some, fresh ones, too. I see how people react on bots' performance and stuff. The point is, you have to remember that with each expansion most of pre-expansion content gets nerfed, sometimes drastically, and with 3.x this goes double for classic content. A good group would just maw through most classic dungeons and classic content in general.
While testing Sea Witch, I configured my server to 'nightmare mode', even for a group, where all mobs have 300% hp, do tripple damage and only give 10% XP, quests give 15% XP, and all drop chances reduced by half except for whites. And still (big thanks to Forked Lightning which cannot miss), bots are able to massacre normal mobs in droves, except for casters maybe, and we only wiped like 7 times total in dungeons (except VanCleef, this guy just goes crazy with his Thrash ability).

2) Well I wasn't aware of that (how it's supposed to work, that is). I only leveled 1 druid in my life, resto. Oh well, need to recheck that code.

3) When it comes to testing a certain class, you really need to compare their DPS against oher bots, not just damage. Dark Ranger doesn't have any AOE abilities, I even had to add an algorithm for her to check and put Black Arrow on targets other than current attack target. But I didn't test her extensively, those extra classes aren't really intended to be balanced. Really I think most of her displayed damage comes from that last tick, which does tons of overkill damage.
As for scaling:
Hit damage is: 150% weapon damage
Tick damage is: 100 + (10 * (level - 40)) + (2 * spellpower), 50% of intellect goes into spellpower. Though ticks are every 2 seconds, not default 3.
So on level 80 she is supposed to do 100 + 400 + 90 (hunter int) = 590 damage, on level 60 it is 360 or so.
But, yes, her attack power is 500% agility + 200% intellect. Plus 15% bonus she gets eventually. She has a cooldown on her Black Arrow, but when she hits something with hp below 20% it's always a kill pretty much. In the past this 500% damage also had x5 crit chance, so it was nerfed once already, heh.

So, speaking about Obsidian Destroyer or Necromancer damage...

4) Yes, it is intentional. A small boost of resistances to compensate somehow for their lack of coordination in close quarters and AOE. It was added way before bots could avoid frontal AOE and find AOE spots.
And extra classes get them as part of their nature or origin. Hero based classes get spell damage reduction just as their W3 counterparts, and some other classes are based off of spell-immune units. In W3 most spell-immune units are still targetable by heals, so I decided to not frustrate players by them not being able to cast anything on these bots, but instead to make them have their 'fun' trying to actually deal any spell damage to them.
As for normal classes, 80 spell resist by itself doesn't really help that much to mitigate spell damage is raids; still, it help when combined with other means to increase group resistances (auras, resistance totems, etc.)

**Comment by thordarsen** [comment]
1) It's just semantics but I _think_ it's more that the players are buffed at each expansion - the ten extra prime spec and revamped talents add a lot. (nerfing mobs and buffing players are essentially the same thing)

2) Yeah, otherwise Warden staff (Lvl 35 BoE epic) is best in slot at 60 and well beyond (with talents it's like 1500 Armor) - also the tanking druid AI may not have enough rage dumps in it - holds aggro fine, but seems to cap on rage often. But that a quick observation, and may be wrong.

3) Maybe I'll drop a training dummy in the middle of nowhere and just have them wail on it for a while.

4) makes sense since they don't really understand the don't stand in the fire thing. Although from fighting Kurinaxx/Azuregos they don't get targeted by some abilities. (Auzregos is fun when you are a caster getting hit by every Mana Blizzard, watching out for the reflect, and then one of the giants aggros)

And again, great work.

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/a4073c99c62eeec8fa4fe8e6bf2ee085c5219196

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/ba2a6e8c1406118bce0de950c60763f1b2de3a57
