### ISSUE TITLE
bots visual and npcbot helper (like in old npcbots)

### ISSUE THREAD

**Issue by slipknat** [trickerer/Trinity-Bots#2]
hi how are u ? tnx for ur efforts i have suggestion. can u add a option to randomize bots visual ((there was a command i use it in old npc bots repack by thanosk but now i cant find it i use every command of mangos and arc emu and trinity core but cant find that command ))!changing their visual by equipment is so frustrairing even worst in raid groups ! and my last suggestion is use npc bot helper(( like in old npc bots thanosk repack)) to save more time and make game more enjoyable !best regards !

**Comment by trickerer** [comment]
Never heard of *randomizing* anything's visuals. By equipment you changle bots' stats firsthand, visuals are just visuals. Are you trying to complete raids with ungeared bots? Anyways you can disable equipment visuals for bots in config - they will use their native model visuals.  
Bot helper and temporarily summoned bots have become obsolete since real gear was added. Bots use real items, and these items have to be saved otherwise they will become lost and clutter your DB with unused entries. So the old system cannot be brought back

**Comment by trickerer** [comment]
[6f8f5af9d](https://github.com/trickerer/Trinity-Bots/commit/6f8f5af9d440dcbea9d1441cc43ae51455598360)
