### ISSUE TITLE
NpcBot - Bot is not attacking when you are as hunter

### ISSUE THREAD

**Issue by nightmare282** [trickerer/Trinity-Bots#204]
Looks like hunter is unlike other melee or magic classes, bot is just not attacking when you are doing range attack. They only attack when you perform melee action (hunter will do melee when mobs are next to them). After I kite a distance and going back for range, bots they evaced and keep following me without any attack.

I tested this on every classes, all melee and even magic classes they are good and bots will attack the target. Seem like only the hunter has this problem.

**Comment by trickerer** [comment]
Last time I tried to extend 'force attack' action to spellcasts also there was a bug when bots start to charge too soon because target is put into combat immediately after spellcast completes and not when it hits the target.

The difference I see between spellcasters and hunter is the kiting range is kinda longer, and also maybe Auto Shot cancels auto-attack.

The only solution here is to increase bots' follow distance `.npcb dist 40` or something to be more on par with you kiting range.

**Comment by nightmare282** [comment]
The ".npcb dist 40" works.

Althought bots are not attacking right after my ranged attack to mob, still need that mob to come a little bit closer. At leaset now they can attack. Before that I always set to 0 as don't want the tank stand too far from me.

Cool. Thanks.
