### ISSUE TITLE
DBErrors.log

### ISSUE THREAD

**Issue by zaicopx** [trickerer/Trinity-Bots#205]
Hi, I'm using your latest npcbot repo.
Every time I create party to npcbot or login with party npcbot, there will be an error like this in DBErrors.log
Is there a way to fix it?
ty

`SQL(p): INSERT INTO group_member (guid, memberGuid, memberFlags, subgroup, roles) VALUES(1, 1, 0, 0, 0)
 [ERROR]: [1062] Duplicate entry '1' for key 'PRIMARY'
SQL(p): INSERT INTO group_member (guid, memberGuid, memberFlags, subgroup, roles) VALUES(1, 1, 0, 0, 0)
 [ERROR]: [1062] Duplicate entry '1' for key 'PRIMARY'
SQL(p): INSERT INTO group_member (guid, memberGuid, memberFlags, subgroup, roles) VALUES(1, 1, 0, 0, 0)
 [ERROR]: [1062] Duplicate entry '1' for key 'PRIMARY'`

**Comment by trickerer** [comment]
This error indicates that group wasn't properly disbanded. I remember fixing such a npcbots-related error in the past, but it started to appear again eventually.

The main problem here is that these errors aren't exclusive to npcbots and may be caused by other factors. Fixing this requires debugging every such case, after they had been found of course.
