### ISSUE TITLE
NPC Bots do not count as players for the Four Horseman encounter

### ISSUE THREAD

**Issue by YunataSavior** [trickerer/Trinity-Bots#21]
Even if you command an NPC bot to stand in Blameux' corner (and the other horseman that does the same AOE thing), she still casts the AOE spell that wipes the party.

**Comment by trickerer** [comment]
From looking at script, Zeliek and Blaumeux need at least one player (and not just unit) nearby. Should be easy

**Comment by trickerer** [comment]
Unfortunately, fixing this will create an exploit, allowing to completely ignore those bosses since their primary spells can only target players (Void Zone 28863, Holy Wrath 28883)

**Comment by YunataSavior** [comment]
In general in the instance, I've been finding that I've been able to "cheese" certain mechanics.

e.g. I was able to group Feugen and Stalagg together (with my bot off tank swapping with me back and forth), then when I got to Thaddius, I was able to completely ignore the polarization mechanic.

Also, in the Gluth encounter (oh boy do I have a lot of suggestions to talk about with Gluth), when Gluth casts Decimate, the NPC bots are unaffected (while me and the Chows will get damaged)

**Comment by trickerer** [comment]
Yes I know all that. I did raid content with bots up to mid Ulduar.

Certain things are easier with bots because of them being non-players and there is no need to add even more exploits. With some hacking they can be fixed I'm sure, but hackfixes are not the highest priority, nor raiding content fixes are.

**Comment by YunataSavior** [comment]
> I did raid content with bots up to mid Ulduar.

For each boss encounter, what was your strategy? What bosses did you have to ignore (or use cheats for)?

**Comment by trickerer** [comment]
It was couple years ago, was playing on 2013 version, 25 mode only.

Flame Leviathan was bugged (could not start) so I had to skip it.

Razorscale - normal DPS through, player activating harpoons, max attack range for bots. Not much tanking involved really. Bots were unaffected by some dmg spells I think (1st try)
Forgemaster - impossible to do normal tactic solo due to constant cauldron on player. 2 tanks (1 player, 1 bot), max DPS (5 tries or so).

XT was broken - constant add waves after hp < 70% or something, just dpsed down with occasional trash switches (me tanking so bots switch to my target always). (1st try)
Assembly was the tough one - didn't know the tactic, so I went for big guy first, then... well I don't remember exactly but caster was interruptable so I at least tried doing him last (8 tries...?)

Kologarn had a bug where player could not be freed from grip unless hand was killed so I just died at start of the fight and bots did the rest. Instakill spell (Death Stare of whatever it is called) was not triggered, probably could not target bots. Wiped 2 times IIRC for some weird damage reasons. Overall stressless fight.

Cat lady - ended up with bot tank, me kiting enraged cats. Fear counter was straughtforward. medium to short attack range for bots. I think I've been killing casts duringthe fight too, but now I'm not so sure (4 tries)

Hodir - never finished. It's hard to group bots in one place, especially in one spot, especially in combat. Bot tanking, me directing movement. Attack range 0. Best result - boss at 30% or so until enrage (10+ tries)

**Comment by YunataSavior** [comment]
What about Naxx? Here are my results from Naxx 10:

**Military Quarter:**
Instructor Razuvious - Tank and Spank
Gothik the Harvester - I split the raid into two between the gates. I have to be on the "Living" side in order to start the encounter, but it would be much smoother if I could put the "non-human" team on the Living side and have them aggro.
4 Horseman - See this Issue tracker. I tried placing bots in all 4 corners, but alas...

**Arachnid Quarter**
All but the 1st (Anub'Rekhan) had zero issues; they were simply tank and spank. For the 1st boss, I had to place my bot tank near the start and force him to STAND, drag the boss to the encounter start, then peel the bots away whenever Anub casted swarm.

**Construct Quarter**
Patchwerk - Definition T&S gear check.
Grobb - I have to make my range STAND in the center and have my bot tank LOSE the tanking role.
Gluth - Oh boy.... This was such a pain in the ass. I can talk more about this (basically I had to do some C++ hard coding to pass thru this).
Thaddius - As mentioned in a reply, I was able to cheese the encounter :/

**Plague Quarter**
I'm assuming all but Heigan will be trivial....

**Frostwyrm Lair**
TBD

**Comment by trickerer** [comment]
Naxx wasn't hard for me at all. I was tanking, plus additional bot tank in reserve. I think I had boss melee damage set to 0.75 at that time since I was testing max loot mod (max loot items increase + all loot template tables ungrouped + client modifications to support that) so all bots were well geared, I only tried to find bugs if any.

Some things worth notice though:

Gothic was rough since I couldn't place any bots on the other side (no such functionality at that point).
Horsemen - underscripted so no wipe mechanics there, just had to run back and forth between bosses to clear marks

Maexxna - gave me a bit of trouble, I think her webs have been stunning everyone so I had to assign a bunch of sacrificial tanks

Patchwerk - had to assign bot tank and act as an off-tank for this fight
Grobbulus - I actually made all my bots ranged (didn't have much melee dps to begin with) and just did standard repositioning (rangedbots tend to spread on one side of the boss). Max attack range and bots don't get any ideas of walking into green shit, most of them anyways
Gluth was kinda disappointing, all he could do is melee the mt, I think only his heal would work, but never happened, maybe it was easy because of kill speed
Thaddius - wiped once due to... lack of dps (speaking of polarization mechanic). And also due to taking a break before the fight so I was like 50% in on the enrage timer

Heigan was messy. I could not make bots follow the pattern so I ended up doing whole battle at the platform. Attack range 0. I think half of the bots died. Bot tanked that too.

Saph wan't hard. Bots are affected by freeze but not bomb. Blizzard pathing was very weird back then (was fixed only recently I think) so I got lucky with that. Bot tank again

Kel'thuzad was a little tricky. Had to mess with auras/totems a little. Overall bots tend to survive because of their res bonus. They are affected by skelly AoE though, and tend to be knocked back much farther than player by banshee - blame TC for that.

Naxx overall is easy. Remember is was destroyed at the launch of 3.x.x by several guilds with their lvl 70 gear?
Also, bots tend to go a little crazy with their heals (calculation on expected hp loss leaves a bit too much room for overheal)

**Comment by YunataSavior** [comment]
I've just tried out Heigan. What would be most beneficial would be if there were a command such as **npcbot command group**. Here's what the command would do:

1. If the targeted bot is casting, then force it to stop casting.
2. Place the bot in STAND state.
3. Force the npcbot to move to the coordinates of the player.

Affects the targeted bot. If the player is targeted, then all bots will be affected.

It seems from your testing that there was a ton of shit that wasn't scripted, thus you were able to faceroll certain challenges (e.g. you shouldn't be able to stand on Heigen's platform when he's on it). Nevertheless, I challenge you to also attempt Naxx 10 now with the following rules:

1. Equip yourself with gear only available from WOTLK 5-man heroics and gear that dropped / would drop from bosses/mobs that you've killed in Naxx 10.
2. No cheats except .cometome and the .npcbot commands.
3. Set boss damage to normal.

I'd like to compare results and see what exactly I'm doing wrong.

**Comment by trickerer** [comment]
> If the targeted bot is casting, then force it to stop casting.
> Place the bot in STAND state.
> Force the npcbot to move to the coordinates of the player.
> 
> Affects the targeted bot. If the player is targeted, then all bots will be affected.

There is a '.npcbot recall' command for it

**Comment by YunataSavior** [comment]
> There is a '.npcbot recall' command for it

Cannot be cast in combat =(

**Comment by YunataSavior** [comment]
Even when I disable the check that determines whether the player is in combat or not, when I issue the command after forcing the npc's state into "STAND", they're still casting...

**Comment by trickerer** [comment]
> Cannot be cast in combat =(

Yeah, sorry.
I believe you can set follow distance to 0 to make bots stand on top of you and only attack when you point the target (tanking dps marked targets will be still higher priority).

**Comment by Parkan1986** [comment]
> Naxx wasn't hard for me at all. I was tanking, plus additional bot tank in reserve. I think I had boss melee damage set to 0.75 at that time since I was testing max loot mod (max loot items increase + all loot template tables ungrouped + client modifications to support that)

А можно узнать что за мод такой о котором тут речь?Максимальный лут и тд и тп?Можно ли поделиться файлами и патчем для этого дела?

**Comment by trickerer** [comment]
Где-то год назад я хотел узнать, можно ли сделать так, чтобы дроп мог содержать больше 18 предметов.
Мне потребовалось менять не только код сервера, но и клиента (примерно в ста местах). Плюс конвертировать все таблицы лута - из референс лута в обычный, а также из групп лута в обычный шанс для всех предметов, что не есть хорошо.
Всё получилось, хоть и заняло несколько дней. Однако это было давно, сейчас тех SQL скриптов мне уже не найти, в остальном же, да, в принципе мне ничего не мешает поделиться этим кодом, я лишь сомневаюсь что кто-то в здравом уме станет его использовать.

**Comment by Parkan1986** [comment]
> Где-то год назад я хотел узнать, можно ли сделать так, чтобы дроп мог содержать больше 18 предметов.
> Мне потребовалось менять не только код сервера, но и клиента (примерно в ста местах). Плюс конвертировать все таблицы лута - из референс лута в обычный, а также из групп лута в обычный шанс для всех предметов, что не есть хорошо.
> Всё получилось, хоть и заняло несколько дней. Однако это было давно, сейчас тех SQL скриптов мне уже не найти, в остальном же, да, в принципе мне ничего не мешает поделиться этим кодом, я лишь сомневаюсь что кто-то в здравом уме станет его использовать.

Если можете поделиться, то я только за. Лишь бы сервак от этого не поломать.

**Comment by trickerer** [comment]
Напиши мне на почту, а я пока попробую накатить код на ласт ревизию тринити.

**Comment by trickerer** [comment]
Seems like I've misread the spell that needs checking.

**Comment by YunataSavior** [comment]
@Parkan1986 

I wrote a Python script that would increase boss drops to 100%

https://github.com/YunataSavior/TC_WOTLK_BossDropLootz
