### ISSUE TITLE
 [AC] [Bug] the NPC which provides NPCBots hiring services can't show custom added npcbots

### ISSUE THREAD

**Issue by zbhcn** [trickerer/Trinity-Bots#265]
**Description:**

the NPC(id:70000) which provides NPCBots hiring services can't show custom added npcbots，can only be summoned by command.

Another suggestion：Can you add the number of robots without limitation,because there are many players, the robots have been hired out, which is not enough.

**Comment by trickerer** [comment]
> Another suggestion：Can you add the number of robots without limitation,because there are many players, the robots have been hired out, which is not enough.

Did I understand you correctly? There is not enough bots you can spawn for your players?
Just how many players are on your server then?
There are 300+ starting bots and enough space for another 200 you can create.

**Comment by zbhcn** [comment]
There are more than 40 players in my server, and each player needs to bring 39 robots

**Comment by zbhcn** [comment]
![image](https://user-images.githubusercontent.com/116956612/204844514-96dd8851-e496-4c85-9e1e-97e339b7138a.png)

**Comment by htc16** [comment]
in my case, the npc does not provide new bots, it only makes available to players the bots that were already created by commands.  is that right or should the npc do the same thing as the command?

**Comment by htc16** [comment]
in my case, the npc does not provide new bots, it only makes available to players the bots that were already created by commands.  is that right or should the npc do the same thing as the command?

**Comment by htc16** [comment]
> NPCBots must be spawned before they are available to players. https://github.com/trickerer/Trinity-Bots#npcbot-hiring-alternatives
> 
> > Down the menu you will find a list of classes of NPCBots. After you select one, a list of **_NPCBots in the world_** available to you will appear.

that's right, it is necessary to generate them manually, one by one, so that they are later available to players on the npc.  I imagined that this could be done more automatically, that is, players could ask for it directly from the npc.  or maybe there was a button that would put x amount of bots already online on first launch server.

**Comment by trickerer** [comment]
Unfortunately, no.
Server administration has to decide how many bots they want to spawn and where.
Bots count as active objects and will load full grids with them, consuming memory and increasing server start times. Plus there can be some serious problems if more that 100 bots are spawned in a single spot. And there are no predefined places to place the bots, since they must be available to players without botgiver, and on small servers there are no sweet spots like this.
So, no predefined locations, means no static spawns, and no automatic spawning.

**Comment by htc16** [comment]
now it became clear to me.  Thanks for the answer.

**Comment by htc16** [comment]
now it became clear to me.  Thanks for the answer.  and thanks for making this available on azerothcore.
