### ISSUE TITLE
[AC] [Crash] Updating Database

### ISSUE THREAD

**Issue by zaicopx** [trickerer/Trinity-Bots#269]
I got latest your AC Npcbot and I got this error while updating database (Fresh install Database)

`Applying update "0000-00-00_npcbot_01_creature_template.sql" '4370FD8'...
ERROR 1064 (42000) at line 7 in file: 'E:\Compile Server\Projects\zaicopx-AzerothCore\AzerothCore-wotlk-with-NPCBots\data\sql\custom\db_world\0000-00-00_npcbot_01_creature_template.sql': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank, dmgschool, DamageModifier, BaseAttackTime, RangeAttackTime, BaseVariance, ' at line 2♪◙
Applying of file 'E:/Compile Server/Projects/zaicopx-AzerothCore/AzerothCore-wotlk-with-NPCBots/data/sql/custom/db_world/0000-00-00_npcbot_01_creature_template.sql' to database 'acore_world' failed!`

**Comment by trickerer** [comment]
Can't confirm of Windows.
If you're using other OS post which one.
I also did test fresh install when made the changes, custom updates always come last so DB structure has to be up to date.
Since you didn't fill the template I have to assume there is a problem on your end.
Try to escape column names with ``` ` ```: \`dmgschool\`,\`DamageModifier\`,etc...
![updates](https://user-images.githubusercontent.com/1254989/205473356-c74d3e11-e2f8-4ba5-a261-5833e5a34866.JPG)

**Comment by Mr-Deadbeat** [comment]
```INSERT INTO creature_template
(`entry`, `difficulty_entry_1`, `difficulty_entry_2`,```

need to use backticks on all the table names on that line mysql is a bit picky on the syntax once you do that it solves the issue thanks @trickerer that comment of yours fixed it kept banging my head against the wall and finally i understood what causes the problem

**Comment by zaicopx** [comment]
Problem has been resolved.  Thanks very much.
