### ISSUE TITLE
Can I let the robot automatically update the equipment

### ISSUE THREAD

**Issue by EvilCalf** [trickerer/Trinity-Bots#273]
Now I need to provide the robot equipment manually

Can I automatically update equipment like the partybot, because bot can call out at any time to attack the Dungeons

**Comment by trickerer** [comment]
You can't. Long time ago bots had stats depending on player, but that system was removed by public demand and replaced with gear-based. But random gear was never a thing with NPCBots. You gear your team as you level ideally, otherwise you have to start somewhere, bots' level of skill can compensate for the lack of gear majorly (well, not totally of course but you get the idea).
