### ISSUE TITLE
[TC] [Bug] [Core] World server crashes following December updates

### ISSUE THREAD

**Issue by ZunaMae** [trickerer/Trinity-Bots#292]
**Description:**

I'm relatively new to this process so I apologize in advance if I missed providing any information.  Please let me know what I've missed and I'll attempt to fill in any requested details.

I was running TrinityCore + NPC Bots 6d399269e5d4 for about a month and it was relatively stable.

I recently upgraded to TrinityCore + NPC Bots 8e4d9313e0.   Following the upgrade, I have had issues with the system crashing (segmentation fault).   Once I started having issues with the server crashing, I downgraded back to 6d399269e5d4.   The crashes continue unfortunately.

I have a theory that I somehow "corrupted" the database following the upgrade to 8e4d9313e0.   It was not clear to me how to apply the database update SQL files, so I just ran them all from sql/Bots/updates after observing errors during startup that the table "tcbots_characters.characters_npcbot_transmog" was missing.   Re-applying all the updates eliminated the startup errors, but I'm concerned I overwrote some existing values when I reapplied all of them.

I cannot seem to determine a pattern for the crashes.   The crashes appear to happen "randomly" -- for example, I can be logged out of the server altogether and it will crash.  Similarly, I can be idling in Dalaran (away from computer) and the system will crash.

Attached are the Server.log and the DBErrors.log files (which appear to be the most relevant of the log files I have. 
 https://gist.github.com/ZunaMae/193c4d8bd837a24fd7945b0b79e21590

The system also generates a core dump.   I am not sure how to provide that file.

This is the start up line from worldserver:   TrinityCore rev. 6d399269e5d4 2022-11-11 21:34:56 +0000 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

I'm running the following operating system:  FreeBSD tc2 13.1-RELEASE-p3 FreeBSD 13.1-RELEASE-p3 GENERIC amd64

**Comment by trickerer** [comment]
There are two things that are kind of worrying. First is that updates after 2022.11 contain new smart scripts, this could potentially cause a trouble on an outdated core. Second is that you get VMAP / MMAP errors. This is kind of a red flag actually.

At least for TC NPCBots sql updates are all 100% reappliable. Worst thing you can do with that is re-generate some default equipment. Just don't do anything to `creature` or `characters_npcbot` tables manually.

You need to find a crashlog for the most recent crash, normally it is gerenerated along with the dump in same Crashes folder.

**Comment by trickerer** [comment]
The crashlog files are text files named the same as dump files.

Generally, yes, this is the process. But you don't need to clone the repository anew, just pull the changes - faster and more convenient. It is best to apply only new updates, unfortunately with TC you have to apply them manually, so - since all update file names contain creation dates, you can just look at your last pull date and find the new updates this way. If you forget it you can also look at your worldserver commit hash and figure the date from it.

There is no way to make new smart scripts to run properly on outdated core in case of incompatibility. You can either go through recent world table updates and try to revert them, or just keep your core up to date. With DB auto-update system you don't downgrade really, unless you keed DB backups for each time you sync with upstream

**Comment by ZunaMae** [comment]
I've gone ahead and re-installed the whole package from scratch (including a fresh database).   System is not crashing as of now.   I'm going to close this issue for now and look for ways to improve my process of upgrading based on the feedback you've provided.

thank you!
