### ISSUE TITLE
colud you provide account sharing npcbots function?

### ISSUE THREAD

**Issue by zbhcn** [trickerer/Trinity-Bots#299]
there are  too many players in my server, colud you provide account sharing robot function? 

Otherwise, if there are five roles under one account and one role employs 24 robots, 120 bots will be required. If there are 50 accounts on this server, 50 * 5 * 24=6000 bots will be required, which takes up too much resources.

So, I wonder if the bots of all roles under one account can be shared?

**Comment by trickerer** [comment]
Account-wide bot ownership won't solve it all. 1200 bots you'll have to spawn using that formula won't be much better.
If you have 50 account then how many players do you have online on average?

For one, AI update delay for free bots could be increased while not in combat and this will solve most of it. That's on me.
Another point of consideration is that if you have at least 10 people online at all times maybe they don't need 24 bots each and 4 or 9 will suffice to enable players to do raiding.
Another trick to reduce the load is to spawn bots somewhere out of reach in a 'grid' kind of configuration 41+ yds from one another and only offer bots through botgiver. 41 yds is important so that bots will not be able to check each other for buffs/heals.

But to answer your question, sharing bots between account charaters is not impossible, it's just that ownership checks will become convoluted and amount of work it's gonna take worries me.

The NPCBots project is supposed to support small servers with not enough players online to begin with, this is why there are not so many of them in the templates, also.

**Comment by zbhcn** [comment]
It's a pity that there are about 10+ players online on my server at any time. As more and more people join, npcbot has been in short supply. At present, there is a total of 600+bots, but there is still a shortage of professional npcbots, and adding npcbots is not convenient. It's a pity to forget it if the workload is too heavy.

**Comment by zbhcn** [comment]
Known bug:
1. BT old 3 Akama shadow boss is not normal, Players and npcbots cannot attack this boss because it seems to be stuck in the shadows.
2. The prince of the storm fortress dropped the orange suit. If you equip the npcbot, it will cause the server to crash.

**Comment by trickerer** [comment]
I am not going to answer off-topic questions here.

Try after https://github.com/trickerer/Trinity-Bots/commit/b7c55630e247fed72e746fdccd173b1404fe1e89. Try to optimize your bots usage, I gave you the recommendations, see how well it goes.

**Comment by trickerer** [comment]
Just realized that binding bots to account creates the same issue as leaving bots equipped at removal, allowing to transfer soulbound items between characters, but in this case - between characters on same account.
So the answer to the original question in no.
