### ISSUE TITLE
 [AC] [Bug] [Spell]the npcbots'dps is too low

### ISSUE THREAD

**Issue by zbhcn** [trickerer/Trinity-Bots#301]
Mages, warlocks, druids, priests,I found out because they always shoot with wands，delayed the spells and spell cycles，sometimes they will be in a daze

**Comment by trickerer** [comment]
Shooting wand is not a problem since bots only use them as last resort, when all other spells are on global cooldown.
And bots aren't your perfect players, don't count on that. They won't do everything perfectly including combat rotation, they will only occasionally have perfect reaction.

The problems with DPS issues like this are:
1. They require strong proofs. The DPS must be **measured** before you can say it's too low or too high
2. You can only compare DPS of a **spec**, not a class in general. The general performance charts exist for PvP but most classes only have 1 main PvP spec, and even then - mostly for different 2v2 class combinations
3. The gear to use must be absolutely top notch for the expansion. That's what game developers optimize balance for mainly and that's where measurements are made at live servers for real players
4. NPCBots' DPS has to be compared to existing preformance measurements of that spec for real players against other classes. Some classes are doing better by blizz design and this fact must be taken into account also
5. Depending on encounter DPS may vary, DPS has to be a **raw** measurement - vs "boss" training dummy

Without proofs even I cannot tell if the issue actually valid and is worth spending hours trying to reproduce it
This is why issue template exists and why issues without it receive "incomplete" label

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/8f593a0707a97e6cd72e1214fc87e7714ac3ff93
