### ISSUE TITLE
[TC] [AC] [Feature Request]

### ISSUE THREAD

**Issue by Day36512** [trickerer/Trinity-Bots#313]
Targeticonmasks are extremely helpful, especially when there are two targets that need to be tanked and healers that need to be split up.

My request is fairly simple: I would love it if you could expand this to bot management and have each individual bot assigned to a particular marker, that would just make a great start to 2023, and be somewhat revolutionary when it comes to the playerbot/npcbot community.

There are certain fights that require more than 2 tanks and groups to be split up in more complicated ways. Having markers assigned to each individual bot would go extremely far in the ability to clear content more smoothly and without cheese.

Huge fan of your project. I really do appreciate your work. Is there any way to help support you?

**Comment by trickerer** [comment]
Hm-m. This makes me think.

So, for starters, there is a priority for target icons for each category which goes from highest to lowest as: Skull -> Cross -> Square -> Moon -> Triangle -> Diamond -> Star.
And then, there is a kind of auto-priority for off-tanks where they check each off-tanking target and prioritize the one not attacking any off-tank currently, this way each off-tank get their own target.

Maybe it would be better to add the ability to set one 'top priority' target for individual bot's (tank and dps only I guess) role(s) so they initially go for that target and when it's dead - follow general rule. Players would have to do it for every bot but only once, on the other hand this may introduce some complications in non-single-player raids where each bots' owner would need to do this additional procedure for their bots for this whole new thing to work (general rules work for all bots in party/raid so raid leader can decide).
For example: 4 tanking targets, each tank get a prioritized tank target which they go for at engage. Heals are sent to the center (or something). DPS are all set to whatever - but the same - priority. This way those 4 icon targets used for tanking marks can be used as DPS marks as well, and in the needed kill order.
This is a bit of simplified example since DPS group don't need to be separated. But still, another benefit of such system is that you don't need to worry about main tank's priority vs DPS down order.
I think this should only apply to icons set in targeting mask, not any icon, this will allow to cache and display creature names in gossip menu: 1) set tanking/DPS targets, 2) talk to bot, 3) gossip menu shows not just icons but creature names

Sorry for the wall of text

**Comment by Day36512** [comment]
That sounds like the perfect solution! The addition of creature names would also be of great value.

**Comment by trickerer** [comment]
The names cache is not shared with players joining the group but I think this isn't that important

> Huge fan of your project. I really do appreciate your work. Is there any way to help support you?

'Not really' would be the short answer.
There are only two ways I see for people to help the project. First, I appreciate when people try to provide (or improve) a translation for all this text used in gossip menu, whispers, etc. How to make a translation is described in README. Second is financial support but I removed the donation link some time ago due to the situation in the world making it almost impossible. I hate to make people try to do something with good intentions only to run into a wall of heartlessness. <- (previous sentence could be ill-formed)

**Comment by Day36512** [comment]
Ah yes, it is so unfortunate that so much of the modding community is affected by the events occuring in the world right now. I know so many good people who are not doing well due to the decisions of others. If a donation link ever becomes available again I'll make sure to send some goodwill your way.

Translations I'm a bit limited in. Japanese isn't really used much in the community, but I'll see if I can take a look at Spanish as well. 

Very much looking forward to trying out your most recent commits!
