### ISSUE TITLE
LFG - solo with bots 

### ISSUE THREAD

**Issue by voarsh2** [trickerer/Trinity-Bots#33]
I edited my LFG source code to the following:
```
enum LFGEnum
{
    LFG_TANKS_NEEDED                             = 0,
    LFG_HEALERS_NEEDED                           = 0,
    LFG_DPS_NEEDED                               = 1
};
```

TrinityCore/client says the group is not viable.

Has anyone else managed to get into a dungeon solo or in a small group with bots?

**Comment by Ryu1254** [comment]
Yes, without modify anything.. I run lfg in dungeon all the time.. even Raid 1 man + 9 BOT.. working pretty good..

**Comment by trickerer** [comment]
Unrelated.

**Comment by voarsh2** [comment]
Hi guys.

Sorry can someone explain to me a bit more?

I see a SOLO LFG "MOD" repo, which is unrelated to this issue

My question was, I edited TrinityCore with that following code and tried to do a Dungeon and I get "group is not viable", so I cannot start the dungeon 

I see b51e8473480c865d9416bda8f7f954c5014d0f61, is that a compatibility fix for sololfg "mod" or just a fix for the bots in general to work with TrinityCore (Dungeon Finder)?

**Comment by Ryu1254** [comment]
I never use the solo LFG mod. because, I always go dungeon with bots. I make a group of 5. Me + 4 bot. with the right composition a normal dungeons group. 1 tank, 1 healer and 2 dps. this will got fine. every time. when I feel like go alone.. then I fly directly to the dungeon. 
another suggestion, if you really really want to solo and use the LFG feature, without any mod beside the NPCBOT mod. what you can do is go with 4 bot.. change their behavior to do nothing. they will just follow you and do literally nothing. 

that's just may style of playing :)

**Comment by zaicopx** [comment]
I use solo lfg + autobalance so i can do dungeon with only me + one or two bots
