### ISSUE TITLE
[AC] [Bug] Cannot Run multiple Dungeon Finder with NPCBots

### ISSUE THREAD

**Issue by Axdrell** [trickerer/Trinity-Bots#358]
**Description:**

Dungeon Finder - when using NPCBots with Dungeon Finder, the first time I am able to join the instance with the NPCBots. Second time the console shows: Wrong dungeon type 0 for dungeon 0.
The Game UI shows  "One or more party members do not meet the  requirements for the chosen dungeon.

**TrinityCore or AzerothCore:**
AzerothCore Trickerer latest branch
**Current behaviour:**

Cannot run multiple instances of Dungeon Finder with NPCBots.

**Expected behaviour:**

Should be able to run multiple instances of Dungeon finder with Bots

**Steps to reproduce the problem:**

1. Create a group with NPCBots with a toon level 23.
2. Assign roles to Bots
3. Complete the first instance of Dungeon Finder
4. Queue up for subsequent instances. If allowed to enter instance, leave queue and retry this a few times. After doing this a few times the error appears.

**TC / AC rev. hash/commit:** 

AzerothCore rev. 2fac8ffe86ac 2023-02-19 09:15:42 -0500 (npcbots_3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)
**Operating system:** Windows

**Comment by trickerer** [comment]
I tried this with level 80 character. After completing a couple random dungeons I got a cooldown, but after it passed I could get into a new random dungeon normally.

Maybe this issue is kinda rare. Maybe it only happens on lower levels. I vaguely remember this happening to me once on low levels (with console error like you described) but this might as well be an AC issue.
In any case, you can always disband your group and create a new one.

Oh, and `2fac8ffe86ac` is not an AC or AC+Bots revision

![rdf](https://user-images.githubusercontent.com/1254989/220004080-b316e0a3-8697-41e6-abdc-2b0a05970fb9.jpg)

**Comment by Parkan1986** [comment]
Disband group of npcbots and gather party again fix issue but only for one dungeon.Regardless of level

**Comment by Axdrell** [comment]
The problem still happens randomly, but I found what could be the cause. When I run a LFG dungeon and complete the instance , there is an entry in the groups table with the toon guid I used to run the instance. The group table field grouptype gets set to 8 (remains 8 even after restarting the server). If I set it to 0 and restart the worldserver the problem goes away and I queue up for LFG with the NPCBots. I have not looked at the code that controls this table. However, every time I find the problem and reset the grouptype to 0, I can rerun the LFG as expected. Not sure this is a bug with the NPCBots code or ACore code.

**Comment by jdubs187** [comment]
I am having this same issue.
And can confirm what Axdrell has said.

**Comment by jdubs187** [comment]
Here's how I'm getting around this.
After dungeon completion, I click on the "dungeon" icon on the minimap and choose "teleport out of dungeon".
After that I right click on my player portrait/frame and choose "leave group".
Then I add all bots back to my group, and the dungeon finder tool works fine and the same dungeon is properly reset.

I'm thinkin this is the intended way, since the bots can't leave group and basically dungeon reset themselves. 
Doing it on yourself works.

**Comment by Axdrell** [comment]
@jdubs187 that makes sense the bots cant leave group and why the LFG gets stuck unless you leave the group and re-add the bots.

**Comment by jdubs187** [comment]
u can watch the groups table when you leave group the entry in "groups" clears from the database :)
