### ISSUE TITLE
[AC] [Crash] [Core] Server Crash related to bot stuck inside instanced area

### ISSUE THREAD

**Issue by perka123** [trickerer/Trinity-Bots#364]
**Description:**

Bot got stuck inside raid after wipe and I heartstoned away, causing server to crash when I try to run it. It's not longer possible to launch the server at all.

**TrinityCore or AzerothCore:**
AzerothCore

**Current behaviour:**
https://gist.github.com/perka123/321083e5d6b9d90d127df73f61f47ca0#file-07031233c254_worldserver-exe_-22-2_20-1-34
Crashes on server start up

1. Run Vault of Archavon with a bot
2. Bot dies in boss fight, I die after
3. Run into dungeon portal, get revived without entering instance
4. Use heartstone to Dalaran
5. Server crash
6. Server keeps crashing every time I try to restart it

**TC / AC rev. hash/commit:** 

AzerothCore rev. 07031233c254 2023-01-07 16:20:55 +0700 (npcbots_3.3.5 branch) (Win64, Release, Static) (authserver)

**Operating system:** Windows 10 64bit

**Comment by trickerer** [comment]
This assertion message means that somehow bot's home position was saved while in instance. I hope you didn't use `.npcbot move` command since I don't remember if it checks for map instancebility (bots can't spawn inside instances)

Don't worry, this is not something you can't fix.
Go to your `creature` table and look for creature `id1`=`70235`. Then replace values in columns `map`, `position_x`, `position_y` and `position_z` with ones of some nearby record **where map is `0` or `1`**. After that the server should start normally. If you had more than one bot and you get another assertion error like this, repeat this process for each of those bots. Creature id is included in debug info

**Comment by perka123** [comment]
I might have done that, can't remember lol

Where is the creature table? In the database in mysql?

**Comment by perka123** [comment]
Okay I managed to fix it despite my zero experience in coding and/or database skills

What I did was I connected to the acore_world database that was in authserver.exe window in HeideSQL, scrolled down to "creature" and did what trickerer told me to do. Then hit Post (Ctrl+Enter) and BOOM, it works again. Don't ask me to elaborate because I did all this by just taking chances :D
