### ISSUE TITLE
Suggestions for deleting bot

### ISSUE THREAD

**Issue by EvilCalf** [trickerer/Trinity-Bots#385]
I wish that player can delete his bot by using name.
Because of the problem that robots occasionally disappear, my server solved it by deleting robots and regenerating them. But delete id or delete target can delete bot that he didnt owned. It may have some problems. So please help add a command that player can delete his owned bot. Thank you so much.

**Comment by trickerer** [comment]
I understand your problem but bot spawns must be managed by administrators only.
Also an issue for this problem already exists: #324.

Now about possible workaround.
From what I understand the main problem is that dismissed bots (ex. at logout) never reach their spawn location for some reason.
One variant is to make a config setting for bots to always teleport to spawn location instead of walking.
Second way is to add a player command which forces all inactive owned bots to teleport to spawn location immediately.

What do you think?

**Comment by EvilCalf** [comment]
Thank you. When the robot disappeared, I used `npcb move`. But sometimes it also ouccur crash like https://github.com/trickerer/Trinity-Bots/issues/324#issuecomment-1461056875. I'm not sure if the reason is the same.
I think the second way is better.

**Comment by trickerer** [comment]
The reason for that crash is `MapUpdate.Threads` set to something other that `1`. Creatures can't teleport between maps safely in that case

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/4cd03765c23ef03c47986c362126c1f97d6b2aae

It will be pushed to main repo tomorrow
