### ISSUE TITLE
Request Bots in use / bots free 

### ISSUE THREAD

**Issue by biglad** [trickerer/Trinity-Bots#460]
Is there a way via command or SQL to show how many total bots, bots in-use, free to wander bots (none spawned ones)

would be nice as admin to see a list of bot info in game or via web

could also be made more complex so u can look up player and list there bots

EDIT
its labelled as bug its a feature request. can u edit plz

**Comment by trickerer** [comment]
Seems like there's a problem with my browser, labels won't change for me. Whatever.

**Comment by trickerer** [comment]
```
SELECT COUNT(`cn`.`entry`) AS `spawned_bots` FROM `characters`.`characters_npcbot` `cn` JOIN `world`.`creature_template` `ct` ON `ct`.`entry` = `cn`.`entry`;
SELECT COUNT(`cn`.`entry`) AS `owned_bots` FROM `characters`.`characters_npcbot` `cn` JOIN `world`.`creature_template` `ct` ON `ct`.`entry` = `cn`.`entry` WHERE `cn`.`owner` != 0;
SELECT COUNT(`entry`) AS `non_spawned_bots` FROM `creature_template` WHERE `entry` > 70000 AND (`flags_extra` & 0xE000000) = 0xE000000 AND `entry` NOT IN (SELECT `id` FROM `creature`);
SELECT COUNT(`entry`) AS `bots_total` FROM `creature_template` WHERE `entry` > 70000 AND (`flags_extra` & 0xE000000) = 0xE000000;
SELECT COUNT(`entry`) AS `bot_pets_total` FROM `creature_template` WHERE `entry` > 70000 AND (`flags_extra` & 0xE000000) = 0xA000000;
```
do prefix DB name with 'acore_' if needed.

There is a `.npcbot info` command but it's only usable in-game on selected player. I think I'll update it to accept name or guid as argument.
There is also a `.npcbot list spawned` command which lists bots in world with some extra info. Wandering bots are easily discernable here since there is always a gap between statically spawned and wandering bots' ids
