### ISSUE TITLE
[TC] [AC] Feature Request: Invisible Transmog

### ISSUE THREAD

**Issue by Day36512** [trickerer/Trinity-Bots#465]
Hey Trickerer!

i was wondering if perhaps you could make a transmog option for npcbots to hide certain slots, namely shoulders, cloak, helm. I know some of these are configurable but it would be nice to be able to apply in game. Current iteration of transmog module allows for this so thought it might be possible here too. 

Thanks!

**Comment by trickerer** [comment]
I'm pretty sure this can be done by setting transmog item id to 0. There is no such option in bot gossip menu currently.

**Comment by trickerer** [comment]
There is one thing I possibly forgot. If you have untrasmogrified items (items that were transmogrified once but since reverted) you will have entries in characters_npcbot_transmog table with fake_id=0 but its meaning now changes - from 'no transmog' to 'hidden'. You may want to set all those to -1 AFTER SQL UPDATE FILE IS APPLIED to retain data state.

**Comment by Day36512** [comment]
Thanks!
