### ISSUE TITLE
[TC] [AC] [Bug] [Core] Not locked variable --- _botsExtras and _botsAppearanceData and _botsData

### ISSUE THREAD

**Issue by zzyyll2** [trickerer/Trinity-Bots#471]
There are some container variables in function GenerateWanderingBotToSpawn, i found no lock when call operator[],
GenerateWanderingBotToSpawn been called not only startup, but at BattlegroundQueue.cpp:264
![image](https://github.com/trickerer/Trinity-Bots/assets/22398806/2116aeb9-6d29-4330-9d83-8eb46f5db8ba)

**Comment by trickerer** [comment]
There is no concurrency in this context so mutex lock would be redundant here.

BotDataMgr::GenerateWanderingBots() is called at startup, yes. And all these containers are accessed for write during this call in a single threaded context.

Then there is a BotDataMgr::Update() which writes to said containers. This method is called from MapMgr::Update() is a single thread.

And BotDataMgr::GenerateBattlegroundBots() which ultimately writes to the same containers. This access does not intersect with other two because they are called separately and in MapMgr exclusive single threaded context.
Finally, GenerateBattlegroundBots() is only called from World::UpdateSessions() which iterates over sessions, updating them one by one. WorldSession also processes incoming packets iteratively.
Full call stack is World::UpdateSessions() -> Session::Update() -> PacketHandler::Call() -> WorldSession::HandleBattlemasterJoinOpcode() -> BattleGroundQueue::AddGroup() -> BotDataMgr::GenerateBattlegroundBots() -> ...


If you've used a profiler or static analysis please give me an insight on what is wrong with this  Otherwise I hope this explanation was clear and useful for you.

**Comment by zzyyll2** [comment]
Got it, thanks.
