### ISSUE TITLE
[AC] [Feature] [Core] need npcbot command like /attack

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#516]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

there is a problem on the Lord Marrowgar in ICC, when he applies a spike to a player, the bot does not attack the spike and the group dies, need an additional command for the bot similar to /attack in order for him to attack the spike and the like in raids

or how to get a bot to attack a spike?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

10b8853

### Operating system

debian 11

**Comment by trickerer** [comment]
There won't be such a command since NPCBots operate on a different concept, otherwise you would need to babysit everything.

There exists a mechanism which forces bots to prioritize some targets above all else and Bone Spikes are already checked there. I tested it just earlier today on AC and it still works.
If it didn't for you then probably you've used attack targeting icon which may possibly be higher priority (don't remember). This is another way to force attack on some particular target when you can't point bots with melee attack.

**Comment by DykeRz** [comment]
thank you :)
