### ISSUE TITLE
[TC] [AC] [Bug] [Core] Sometimes robots are always in a combat state

### ISSUE THREAD

**Issue by lmzml** [trickerer/Trinity-Bots#533]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

In dungeons, sometimes the robot remains in a combat state, even if the player has already left the battle, causing the robot to be unable to recover magic. After the player dies, the robot will not resurrect and cannot communicate with the robot. Strangely, some robots are normal, while others are not.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) ready...

**Comment by trickerer** [comment]
This is a common AC bug (due to old buggy threat system) where you can't leave combat because you're in a threat list of some creature, which is sometimes invisible / untargetable. This happens to both players and bots. Easily cured with `.npcbot recall tele` or `.npcbot kill`.

If you're sure that in your case only bots are affected then answer these questions:
1) What dungeon?
2) What coordinates? (`.gps` on self)
3) What do `.debug threat` and `.debug hostil` show?
4) Does player enter combat if affected npcbot is recalled or killed

**Comment by lmzml** [comment]
OK,Thanks!
