### ISSUE TITLE
 [AC] [Crash] [Core] After the newer version is merged and compiled

### ISSUE THREAD

**Issue by lemonmomomo** [trickerer/Trinity-Bots#546]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

After merging and compiling with the new version of AzerothCore, the game cannot enter the battlefield and will crash!
I don't know whether it is AzerothCore's problem, so I sent it here first, please understand!
[7dcbf7c6189e+_worldserver.exe_[28-6_18-9-34].txt](https://github.com/trickerer/Trinity-Bots/files/11893101/7dcbf7c6189e%2B_worldserver.exe_.28-6_18-9-34.txt)
“https://gist.github.com/”I may have made some restrictions on this URL, causing it to be unable to open, I tried many times and failed, so I sent the crash log file here! Please understand!

### Expected behaviour

Both squads and non-squads should be prompted to enter or not enter, not crash!

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

Revision: AzerothCore rev. 7dcbf7c6189e+ 2023-06-25 15:04:20 -0300 (master branch) (Win64, RelWithDebInfo, Static) Date 28:6:2023.

### Operating system

win10 x64

**Comment by trickerer** [comment]
For some reason, June 2023 updates don't take into consideration Battleground maps.
Attempt to cast BG map to `InstanceMap` instead of `MapInstanced` returns nullptr which causes crashes in BG. I got several of those right away after merge. This is just another one.
This issue wasn't fixed in upstream in 2 weeks so I guess it's up to me then. I'm not in a hurry though.

P.S. looks like you aren't using npcbots version of autobalance. Crashlog points to `Autobalance::OnCreateMap()` body at line 1718 but in my version this method only starts at line 1814.

**Comment by lemonmomomo** [comment]
@trickerer Thank you for your patience.
I don't use the npcbots version of autobalance. In fact, I think if I had your npcbot in a single player game, I wouldn't need mod-autobalance anymore. I made autobalance exist unilaterally, but didn't enable it in the game. Since I hadn't looked at the previous problem, I didn't realize that it was also a culprit in the crash problem.If I were to recompile I would use the npcbots version of autobalance.
No hurry, I will patiently wait for your update.

**Comment by lemonmomomo** [comment]
@trickerer   thank you.
The same ac version, without mod-autobalance or compiled with npcbots version of autobalance, did not crash.
