### ISSUE TITLE
[AC] [Question] [Group/Core] queue as group， Occasionally can't go into the battlefield.

### ISSUE THREAD

**Issue by lemonmomomo** [trickerer/Trinity-Bots#551]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

When I reteam, click Squad,Occasionally can not enter the battlefield, display queue status, restart the world server, click the squad again can enter the battlefield.
I wonder what the reason is?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 7dcbf7c6189e+ 2023-06-25 15:04:20 -0300 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

win10  64

**Comment by trickerer** [comment]
This should've been a bugreport.

The revision you provide isn't a part of AC+bots repo yet. I assume you're using a patch, But you didn't provide a patch version.

Can't confirm on https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/648d6dfa1a11181f4b14c3a961e42a8c76203154. After winning / leaving BG with my own bots I can queue to other / same BG again.

The only thing I can think of (since translation is horrible) is the restriction that was added recently. You can't queue for BG **as single** if you have bots in group - you have to queue **as group**.

**Comment by lemonmomomo** [comment]
[61c5ac4](https://github.com/trickerer/Trinity-Bots/commit/61c5ac4d84ebddb7e9095a95e99e789a2a17db2d) 
I merged the patch you updated yesterday
I find it strange that I have so many robots outside of dynamic and static. When I join the battlefield as a group, it shows that I am in the list and there is no pop-up to enter the battlefield, but this is an occasional situation. After leaving the group, a single person can be discharged into the battlefield. Once worldserver is restarted, I can enter the battlefield as a group and it can enter normally again.

https://github.com/trickerer/Trinity-Bots/assets/122801033/ff7bbdbc-6043-425f-b184-b53a612e3aff

**Comment by lemonmomomo** [comment]
When I was arranging the battlefield in groups, I did not know why I was prevented from entering the npc robot, causing me to be in the list state. I personally feel that there are not enough robots, but I have been playing alone, so I negated my hypothesis!

**Comment by trickerer** [comment]
Find in your worldserver.conf this row:
`Logger.npcbots=2,NpcBots Server'
and change in to `Logger.npcbots=5,NpcBots Server' to enable debug logging. See what console shows when you get this problem.

**Comment by lemonmomomo** [comment]
Logger.npcbots=5,NpcBots Server

**Comment by trickerer** [comment]
> Logger.npcbots=5,NpcBots Server

Why do you copy this here? Run the server and see what errors you get.

**Comment by lemonmomomo** [comment]
@trickerer&nbsp;

I'm sorry, there was something wrong with the Internet just now, and the web page couldn't be opened when I sent a message.

I will set&nbsp;logger.npcbot=5

**Comment by trickerer** [comment]
Ok

**Comment by lemonmomomo** [comment]
[Server.log](https://github.com/trickerer/Trinity-Bots/files/11914591/Server.log)
I don't know if it's this log.
I set Logger.npcbots=5 and Restart Server.
queue as group, and Finish the battle.
Without quitting the game, my group can continue to platoon battlefield, and there are no mission issues.
When I quit the game, after some time to log on to the game again，queue as group again.
In the list of battlefields, but not  enter the battlefield.
Please help to have a look, thank you!

**Comment by trickerer** [comment]
The problem is probably you just don't have enough spare bots. You have 100 wandering bots and 92 static bots. It' hard to tell how many bots of extra classes there are, but only bots of normal classes can enter BGs and there are dozens of bots of custom classes out there.
Log shows that only 13 Alliance bots and 9 Horde bots were queued but I'm not sure why you didn't receive any error there.

1) What is your AB config in `battleground_template`?
2) What is your `NpcBot.WanderingBots.BG.TargetTeamPlayersCount.AB` in worldserver.conf?

Also, you're surely not using last version of bots (or merge wasn't complete) otherwise you wouldn't have had a spellbreaker in queue (Nerisen).

**Comment by lemonmomomo** [comment]
![battleground_template](https://github.com/trickerer/Trinity-Bots/assets/122801033/7fe0c714-d854-48ad-91c1-de9a45811654)
I'm sure I pulled and merged NPCBots v5.4.103a.Bugfix.Enhancement.
I had a spellbreaker in queue (Nerisen)？I don't know. What's the problem?
 in worldserver.conf：NpcBot.WanderingBots.BG.TargetTeamPlayersCount.AB = 12

**Comment by trickerer** [comment]
Alright, I'll try to reproduce your conditions.

> I'm sure I pulled and merged NPCBots v5.4.103a.Bugfix.Enhancement.How do I see if I merge complete?
I had a spellbreaker in queue (Nerisen)？I don't know. What's the problem?

Check your botdatamgr.cpp line 198. It has to be
```
        {BOT_CLASS_SPELLBREAKER, 14u/*1610u*/},
```

**Comment by lemonmomomo** [comment]
@trickerer 
![botdatamgr](https://github.com/trickerer/Trinity-Bots/assets/122801033/247c33c4-6988-429b-bd72-9acb5c8981bc)

**Comment by trickerer** [comment]
Ah, sorry. Nerisen isn't a spellbreaker, it's a rogue, mistook him for Narsen.

**Comment by lemonmomomo** [comment]
> Ah, sorry. Nerisen isn't a spellbreaker, it's a rogue, mistook him for Narsen.

queue as group， Occasionally can't go into the battlefield.Is this the cause?

**Comment by trickerer** [comment]
> queue as group， Occasionally can't go into the battlefield.Is this the cause?

No.
The only lead I have is that for some reason 13 Alliance and 9 Horde bots were generated instead of 12 and 10.

**Comment by lemonmomomo** [comment]
> > queue as group， Occasionally can't go into the battlefield.Is this the cause?
> 
> No. The only lead I have is that for some reason 13 Alliance and 9 Horde bots were generated instead of 12 and 10.
Thank you very much for your answer.
Alright then. If there's anything else I need to provide, I will.
I will try to set WanderingBots to 0 and see if this problem occurs.

**Comment by trickerer** [comment]
Debugging shows that the actual problem comes from a bug in core which (essentially) eventually causes any BG queued group of size greater than minimum players number for BG type to be only fit for a premade vs premade match, resulting in player's group never getting invited to a normal match where bots are queued, just because minimum number of players is set to 0.

I recommend setting minimum players for BGs to at least 5 and only try to queue in a group if this size minus one to avoid this bug.

**Comment by lemonmomomo** [comment]
![微信图片_20230701093136](https://github.com/trickerer/Trinity-Bots/assets/122801033/bc50dd28-17a1-4a30-ba0c-4dd490fd461b)
in fact，battleground_template：The default value should be the one shown on the diagram
The minimum number of people =0 is my personal behavior, which is really embarrassing when something goes wrong.
After the configuration as you said, there is no problem at present.
If it is the problem of ACcore itself, I really don't know how to reflect it to AC, or will AC's contributors solve it?
Thank you for taking the time to help me.
