### ISSUE TITLE
[TC] [AC] [Question] [Group/Core] Preventing off-tanks from taunting from player

### ISSUE THREAD

**Issue by TobiasOeser** [trickerer/Trinity-Bots#553]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

From what I've read, multiple (off-)tank bots can coordinate among each other, but I'm having trouble having my off-tank coordinate with myself when I'm playing the "main tank".

For example: If I'm fighting two targets, I'll assign the off-tank icon to Mob A (that part works well), and tank Mob B myself. 
While the off-tank bot does focus on fighting Mob A, it seems to regularly taunt my own Mob away from me. 
I assume it does that because it does not know I'm a tank.

Is there a way to tell off-tank bots that I'm the main tank, so they only taunt mobs away from non-tank bots (or if the mob in question has the off-tank target icon)?

There is a workaround by deactivating the off-tank role when not needed, but that only works out of combat and is mildly cumbersome.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 11a9689b3eda 2023-05-20 17:39:48 +0700 (AzerothCore branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

Win10

**Comment by trickerer** [comment]
I checked the code and it seems like there is no such check. Needs a fix.

**Comment by neotms** [comment]
I did some work on this issue recently on a fork that I maintain for personal use. The following two commits include all my changes on bot behaviour for this.

This issue is happening when NPCBots look for a distant target in need of taunting. There were no checks to stop taunts from players who are assigned as a tank (either in LFG or in raid UI). My changes add several conditions which identify players as a tank or off-tank and prevent the bots from taunting when not needed.

https://github.com/neotms/AzerothCore-wotlk-with-NPCBots/commit/789d140500e4aae996d47bffa8991745e1ba1173

https://github.com/neotms/AzerothCore-wotlk-with-NPCBots/commit/769ff4d449a60ff241a4e1760cb05dec4691ac2e

**Comment by trickerer** [comment]
Should be fixed by https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/8eef51ca0fa2f6b89db8bd251dd0aba7394dde8f
