### ISSUE TITLE
[AC] [Question/Feature] [Group/Spell/Core] How to equip tabard to hired bot?

### ISSUE THREAD

**Issue by jottongbao** [trickerer/Trinity-Bots#556]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [ ] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

There isn't any option to equip tabard to bot. Is there anyway to equip tabard to currently hired bot? I tried to connect dbc and found some code, but couldn't find tabard slot there too.

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
The ability to equip tabard wasn't included in equipment implementation. Reason was that equipped [Guid Tabard] will not display properly since bot can't have a guild. Also tabards don't have stats, although shirt slot is available still.
Not sure how difficult it would be to extend the system to support tabard slot exactly.

**Comment by trickerer** [comment]
I don't think this is going to be implemented, I'm sorry.

**Comment by ark-royal-91** [comment]
@trickerer Would it be possible to request a reconsideration of this in light of repacks that _do_ make use of the tabard slot as a stat/spell carrier, such as Dinkledork's, or is there a serious technical limitation preventing it?

**Comment by trickerer** [comment]
> @trickerer Would it be possible to request a reconsideration of this in light of repacks that _do_ make use of the tabard slot as a stat/spell carrier, such as Dinkledork's, or is there a serious technical limitation preventing it?

Putting current feature request aside, I don't support repacks, can't afford that. Simply said, repacks are an inexhaustable source of trouble for a developer.

**Comment by Day36512** [comment]
Putting the request aside, that's a really sour attitude to have toward a community that heavily supports your work and offers a lot of exposure, testing and feedback and may lead to people who want to compile their own in the future. With your logic it would seem you don't support custom content of any sort, basically what a repack is anyway, which is ironic considering the module itself is custom. 

That said, I understand that it can be obnoxious to have a feature not work and people bug you about it because the repack owner didn't do something correctly when they compiled or intentionally removed a feature, but that's no different than any normal server. 

Just my two cents.
