### ISSUE TITLE
[TC] [AC] [Question] [Core] bots join in the arena?

### ISSUE THREAD

**Issue by zhuyaozi** [trickerer/Trinity-Bots#588]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

hello ,may i ask how to make bots join in the arena? i find a variable in worldserver.conf，“NpcBot.Enable.Arena”，i set it = 1。but it seems not working.

### TrinityCore or AzerothCore

AzerothCore

**Comment by Russianranger** [comment]
Arena functionality has not been added, only some very basics in case someone wants to add it themselves.

**Comment by trickerer** [comment]
This config setting only manages bots' ability to enter arena maps. They can participate in matches with plyer owner as auxillary team members, but they cannot form "bots only" teams. Yet.

**Comment by geektcp** [comment]
Adding robots to arena is a great suggestion.

**Comment by Frann94** [comment]
Im not able to get the bots into arena and I have the config set to 1 and I have the skirmish command enabled
I have two players with 1 bot each one, each in it's own party group, but none of them is able to que as a group since it fails with the error "Incorrect party size"
If I run the command for 2v2, it says player #botname not found
If I run the 1v1 between the players, both players must not be in a group but then the arena start but the bots are not summoned

(Sorry to bring this up again, I was not sure about creating another ticket)

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/88e176fc52defc1164612188240ccb03bce2f43d
