### ISSUE TITLE
[TC] [AC] [Question/Feature] BWL suppression room

### ISSUE THREAD

**Issue by Grimfeather** [trickerer/Trinity-Bots#595]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I was trying to progress through BWL with NPCbots
When I came to the suppression room I ran into a problem.
Normally a rogue disables the suppression devices, but I'm not playing as a rogue.
So my question is if we could somehow ask a rogue NPCbot to disable them
Or maybe temporary take over control of a rogue NPCbot so we can disable them ourselves.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 864e40557e61 2023-07-15 15:47:44 +0700 (npcbots_3.3.5 branch)

### Operating system

Windows 10

**Comment by zaicopx** [comment]
![Screenshot_2023-08-09-18-15-48-42_572064f74bd5f9fa804b05334aa4f912](https://github.com/trickerer/Trinity-Bots/assets/68382531/9db2a60c-de04-4d7a-a13d-ce9782879052)

You can join this discord because dinkledork has .lua for disable surpression room.

Here link: https://discord.com/channels/857134283130011649/1123437072380866630

**Comment by Grimfeather** [comment]
thank you, I'll try it.

**Comment by Grimfeather** [comment]
Thiis
