### ISSUE TITLE
[AC] [Question] [Core] Every worldserver restart creature template entry increase

### ISSUE THREAD

**Issue by podmepodme** [trickerer/Trinity-Bots#607]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I noticed that every time the worldserver restarts, creature template entries increase. In the database,  there is still the original value, but when using the command `.npcb list spawned` there is an entry creature template mismatch. I am only "spawning" wandering bots and BG bots. Is this intended behavior?

### TrinityCore or AzerothCore

TrinityCore

### Operating system

Ubuntu 22.04

**Comment by trickerer** [comment]
This is intended.

This is a way to work around client caching NPC names, since bots get selected at random.
Although that was a quick solution from the get go. It could also be a fixed creature entry increase, equal to number of total existing wandering bot entries plus one, but this also assumes an available full id range at this offset and also requires client cache purge when new custom npcbot entry is created.
So currently we are stuck with this system. If you find your generated bots' ids too high for comfort you can reset this counter in worldstates table to 70000, don't forget to delete client cache.
