### ISSUE TITLE
[TC] merge Question.

### ISSUE THREAD

**Issue by Krutok** [trickerer/Trinity-Bots#612]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I wanted to ask what the update interval is now. When you release a new NPCBOT patch, will it also be available in your TC fork immediately or with a week delay?

And how many days weeks ago is your fork compared to TC?
I ask because I may plan to take the fork from here again, which then already contains the patch.

### TrinityCore or AzerothCore

TrinityCore

### Operating system

Debian 11

**Comment by trickerer** [comment]
As of today (22 Aug 2023) TC+NPCBots repository is up-to-date with TC base 3.3.5 from 20 Aug 2023 (https://github.com/TrinityCore/TrinityCore/commit/1bea4aab456a01d89b87344d47cf345cd68f2d85)

Each Saturday changes get pulled from upstream (base TC 3.3.5 branch), if merge is successfull then new patch is released the same day, this never changed. Patches get updated using the forks, not vice versa.

Last update was delayed because of major changes made in TC 3.3.5 branch, it took some time to go through bots code and update it.

Also worth mentioning that building TC on Windows now requires Visual Studio 2022 which I don't have on my dev machine currently, so future updates my get delayed if they don't succeed via automerge. But really I don't think there is much to worry about - 3.3.5 TC branch doesn't receive frequent updates anyway.

**Comment by trickerer** [comment]
Well I have no idea why PRs are limited to collaborators, google says GH in some emergency state or something. I don't have any temporary restrictions enabled.

TC automatic merge was failing because I forgot to update automerge repository. Merge is completed now https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/a605960be314efa29c2e4513e8e34c1a1723d902.
I'm not updating the patch since I can't run it myself to check if it actually works and won't bug out with basic functionality or even crash at startup.

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/9e551a93d4d9d04cfb9c195025e495ef4e0eca76
Not tested.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/5da5b7193a8f79587e9db44b5a589d45278162e6
