### ISSUE TITLE
[AC] [Question/Feature] [Group/Spell/Core] in the battleground NpcBot cc time error

### ISSUE THREAD

**Issue by YuLongGongWu** [trickerer/Trinity-Bots#629]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

1 npcbot mage sheep another npcbot 60 second
2 npcbot warlock fear another npcbot 20 second
3 npcbot paladin repentance another npcbot 60 second
4 if i want npcbot in battleground wear pvp gear  what should i do ?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

commit id da30653363b8103fde6b9d643e280d61b520ecaf

### Operating system

ubuntu20

**Comment by trickerer** [comment]
I don't remember how long ago that was, but I made it so that for world bots in BvB combat normal pvp rules for CC duration do not apply, as experiment. Maybe it shouldn't be the same for BG bots, not sure, I don't get much feedback on that.

PvP gear you cannot control currently. Gear selection in this regard follows these rules:
- Only level 80+ bots try to select PvP gear
- PvP gear is selected for: head, shoulders, chest, waist, legs, feet, wrists and hands
- PvP gear is checked by presence of resilience stat
- `10%`: PvP gear for all slots with ilvl >= 264
- `10%`: PvP gear for all slots with ilvl >= 245
- `30%`: PvP gear for all slots with any ilvl
- `50%`: Any gear (may contain PvP pieces)

**Comment by YuLongGongWu** [comment]
thank you for your reply
and maybe we can use plan B
I really dont care NpcBot wear pvp gear or not,I do care resilience. 
we give the NpcBot in the battleground a fixed resilience value , like 1200?
