### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] DK Runeforging

### ISSUE THREAD

**Issue by craigdbarber** [trickerer/Trinity-Bots#632]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hello. I've been playing with DK npcbots and noticed that there doesn't seem to be an option within their gossip dialog to put runeforge enchantments onto their weapons. Currently the workaround I've found is find the itemEntry for the item I want to enchant, and then manually add the enchantment to the world.item_instance table.

One outstanding question with this approach however, is that the Runeforge enchantments have a skill requirement for Runeforging. I'm not sure how skills are determined for the bots, so I'm not sure if they're even able to get the benefit of the enchantements. Will update with further testing.

My main question is, is there a known solution for this? Or else, is this feature planned to be added?

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. afc050980cd6+ 2023-09-19 22:08:56 -0400

### Operating system

Ubuntu 22

**Comment by trickerer** [comment]
Runeforging was never implemented for DK bots. The reason here is that using it requires spellfocus (friggin runeforge gameobject). I could just set enchantment to the item directly of course, but then there is no animation or other visual indication of the enchantment being applied.
Right now the only way to apply runeforging to bot weapons is to play as DK: enchant an item and give it to bot.
As for plans, isn't a high priority, doesn't seem a crucial part of DK gameplay.

**Comment by craigdbarber** [comment]
Thanks for the follow up. Appreciate the workaround. Of note, I tested my DK bots having runeforge enchants, and they do in fact work for them.
