### ISSUE TITLE
Any video of how to install NPCBOTS in your server?

### ISSUE THREAD

**Issue by Machalote33** [trickerer/Trinity-Bots#636]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Any guides on how to install NPCBOTS in your server? ty

### TrinityCore or AzerothCore

TrinityCore

**Comment by trickerer** [comment]
Well I didn't make one.

But it isn't that hard, in fact it's mostly the same process always.
In case of patch you clone an unpatched repository, download the patch, apply it, apply SQL files to DB(s) if any, merge config if needed, build and that's it.
In case of patched repo you use it as you would any other repository. Which is just the above steps minus patching and config merge since there's no extra code nor additional config.
I'm sure you can find a guide for both cases on youtube, even if it isn't NPCBots.

**Comment by Machalote33** [comment]
Ok I will try my best to install it thank you for replying!
