### ISSUE TITLE
[TC] [AC] [Question] [Core] Does non-wondering bots keep grid loaded?

### ISSUE THREAD

**Issue by SouthMemory** [trickerer/Trinity-Bots#639]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

in worldserver.conf, "Wandering bots keep grids loaded, increasing CPU and memory usage."
I wonder does normal npc bots (not wondering bots) also keep grids loaded?

if so, how to prevent them from keeping grids loaded?

### TrinityCore or AzerothCore

TrinityCore

**Comment by trickerer** [comment]
The problem with loaded grids mostly affects AzerothCore servers, the reason being is that there is no grid unload mechanism there (TC has it).
When bot enters a grid they load it automatically (just like players) to spawn creatures to kill, enable hiring using botgiver and some other interactions. Normal and wandering bots are the same in that regard, only wandering bots constantly move from one grid to another so while static bot keeps 1 grid loaded at most, wandering bot may enter several grids and keep them in memory until they (all but one currently active) get unloaded.

Grid load cannot be prevented, but you can reduce the negative effect.
Since you use TrinityCore you can enable grid unload in config. Reduce the amount of constantly loaded grids - use less bot spawn areas throughout the world. By spawning bots in (relatively) uninhabited places you lower the amount of CPU burden. But much more CPU usage increase comes from bots being spawned too close to one another. To make CPU usage minimal for static bots you theoretically have to spawn them in completely barren place and about 50yds from any other bot. Some admins use just that and only enable hiring bots using botgiver npc.

**Comment by SouthMemory** [comment]
I am trying to replace all mobs in world using normal or wandering bots, But I was afraid that the cpu or memory burden would be too too high.
would that be a problem?

**Comment by trickerer** [comment]
Oh so this is where it comes from.

Well, that's most likely impossible for many reasons, mainly because NPCbots do not fulfill the role of mobs around the world. Not enough variety in both visuals and abilities, no interactivity, no speech, etc. NPCBots were created to help players, not to oppose them. Wandering bots are just an experiment, although they do act adequately in straight PvP (sometimes) they can't do much outside of just combat.

But to answer your question.
Memory shouldn't be a problem if your server machine has enough of it to keep most grids loaded, each bot uses a bit more memory than a normal creature, but I don't think you plan to replace every single creature with a bot.
CPU on the other hand is bound to become a problem once the amount of bots exceeds several thousands, at 10-15k I would expect lags even using 8 cores for the worldserver, Release build. Bots use pretty complex logic both in and out of combat, checking their surroundings for many different things, this means CPU usage grows exponentionally the more bots there are, this is true for normal creatures too, but with bots this rate although not exteme still pretty high. There are also preformance bottlenecks like aura stacking, I tried to reduce its effect on bots but this is still a problem with high amount of creatures having the same aura in one place.

I would suggest an experiment: spawn as many bots as possible until you encounter lags, somewhere in ocean, 5-15 bots per spot, 30yds between spots. This should give you some idea of how many bots your server machine basically can handle in terms of CPU usage. You will be able to then remove them using delete free bots subcommand

**Comment by SouthMemory** [comment]
yes, I just want to create some bot for players  to kill, and I thought battling against mobs would be more fun because they are much more smarter than original creatures.
So I want them to have the same grid loading mechanic like original creatures, only activated when necessary.

**Comment by SouthMemory** [comment]
can i ask what's the minimum change I cam use to make the wanderer stop wandering?
The code is quite complicated for me ...

**Comment by trickerer** [comment]
You could try to force travel node to be always the same. Go to `bot_ai::GetNextTravelNode(...)` and make it always `return _travel_node_cur;` This should cause wandering bots to just mill about their spawn point and also return there after death. Be aware that this will disable BG bots movement as well.

**Comment by SouthMemory** [comment]
yes, your method works, but it's not what I wanted.
I just want the bot to wander around it's spawn location, with a wander distance like 50 yards, I don't want it to stand still
Is there any suggestions?
I tried a few ways, but it does not work, or will collapse the service

**Comment by trickerer** [comment]
> yes, your method works, but it's not what I wanted.

That what you asked for. Why did you ask for something you didn't want?

Mill mechanics are handled inside `bot_ai::Evade()` including distance and timer. Look for `if (nextNode == _travel_node_cur)` and `evadeDelayTimer`

**Comment by SouthMemory** [comment]
Thank you so much! @trickerer 
I followed your advice, did something under `if (nextNode == _travel_node_cur)`, and it worked.
So grateful!
