### ISSUE TITLE
Using consumable on bot does not remove it from player's inventory

### ISSUE THREAD

**Issue by GitGoppy** [trickerer/Trinity-Bots#64]
3.3.5a Trinitycore

Use any consumable on the bot's list using it's right click UI.
Infinite consumable.

**Comment by trickerer** [comment]
From [v4.0.591a](https://github.com/trickerer/Trinity-Bots/commit/4688efa40d)

``You can now give consumables to your bots (through gossip menu). Item is not taken (yet) since bot buffs are not saved (...yet?)``

This is intended because it's just a basic implementation and probably won't change in the near future.

**Comment by GitGoppy** [comment]
Ah, ok
