### ISSUE TITLE
[TC] [AC] [Feature] Enhance the features of NPCBots Weapon Bank

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#642]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

The npcbots weapon bank is a great feature.
I think if you withdraw the list from the weapons bank,
It is possible to further increase the function of displaying the GS score of each equipment,
Helps players make storage adjustments between weapon banks and backpacks when equipping NPCBOTS.

Please consider whether it can be achieved?
Thank you~

### TrinityCore or AzerothCore

Both

**Comment by trickerer** [comment]
This could be added initially, but I use a non-default font there so wasn't sure if that would extend entry too much (on average) for comfort. It isn't nice when item is listed using 2 rows effectively because of additional space GS string takes: ` (GS: 123)` (10 additional symbols). Of course this is already used in equip dialog but that list tends to be much shorter than a full page which is easily reached when player keeps a pile of varied bot items. I would say that tolerable average rows count per bank item is about 1.1-1.15

**Comment by moncat2005** [comment]
If there are too many line breaks after the equipment name in the list with the GS character, it will indeed affect the experience.
Can it be arranged in descending order of equipment GS score by default?
A classification list of matching equipment, such as by head, shoulder, chest... List optional equipment?

**Comment by trickerer** [comment]
> Can it be arranged in descending order of equipment GS score by default?
A classification list of matching equipment, such as by head, shoulder, chest... List optional equipment?

Bot gear bank items are sorted by name, the order is hardcoded at container type level (std::multiset with custom comparator functor set at compile time). So options here most likely won't get introduced.

**Comment by moncat2005** [comment]
This optimization has started to be used and is much more convenient than before.
If it could be sorted in descending order of GS score, that would be even better.
