### ISSUE TITLE
[AC] [Request more battleground implementation] [Core] Please implement more battleground and make them works, it's great!

### ISSUE THREAD

**Issue by rogerc66** [trickerer/Trinity-Bots#643]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I have tried the 3 bgs and it's huge fun to play in them, hopefully all of the rest bg will be working like that, it will make this game live again and greatly increase the life time of the project!

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

Azerothcore lastest

### Operating system

Ubuntu 22

**Comment by xBarselonx** [comment]
Согласен идея отличная. trickerer, а возможно реализовать случайное БГ из 3-х которые ты реализовал?

**Comment by DykeRz** [comment]
Успехи?

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/1e89bc274e0835e333753ffb141ed586e79c61d8

I think arenas take priority over remaining 2 BGs (and because I have no experience with those)
Note that this issue will be closed after above changes are merged
Random BG probably won't happen
