### ISSUE TITLE
[TC] [AC] [Feature] [Group] Request enhance NPCBOTS's intelligent ability to avoid ground damage

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#652]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

When NPCBOTS is in a damaged position, the current code cannot intelligently avoid it. 
I'm not sure if it's possible to improve the AI program so that NPCBOTS can promptly detect themselves in a damaged position, respond accordingly, and avoid this position.
Here are my personal assumptions：
You can consider borrowing the player's avoidance position/direction while maintaining the original professional attack distance, making a circular motion with the boss as the starting point, taking a basic number of steps, and then judging again until you leave the damage position/range from the ground position.
The triggering of this event also requires determining the profession, which is applicable to DPS and healing profession objects in the near and far.
You can also consider selecting whether to enable it in the configuration file or NPCBOTS dialogue profession feature.

### TrinityCore or AzerothCore

Both

**Comment by trickerer** [comment]
Area of effect damage avoidance exists since f4f66672a5f08. It just doesn't work everywhere because some damage sources can't be detected automatically and require some additional code. And yes the last resort for safe position selection is player owner.
This also doesn't work when damage source is the same unit as attack target (ex. boss casting Hellfire type spell).
