### ISSUE TITLE
[TC] [Build] Multiple "was not declared in this scope" while make.

### ISSUE THREAD

**Issue by Louisina-TSS** [trickerer/Trinity-Bots#654]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Multiple "was not declared in this scope" while make.

Here cmake and make logs:
[cmake.log](https://github.com/trickerer/Trinity-Bots/files/12883993/cmake.log)
[make.log](https://github.com/trickerer/Trinity-Bots/files/12883997/make.log)

### Expected behaviour

Build without error

### Steps to reproduce the problem

1) git clone TrinityCore (-b 3.3.5) and Trinity-Bots
2) move NPCBots.patch in TrinityCore folder, and apply patch.
3) create build folder, go in it, use cmake command with -DCMAKE_INSTALL_PREFIX, then make.
4) errors at 17% in src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_ai.cpp.o

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

a7abceed89

### Operating system

Ubuntu 20.04.6 LTS

**Comment by trickerer** [comment]
Patches weren't updated for a while since I'm temporarily unable to confirm core stability due to technical issues on my side.

Patches repositories on the other hand continue to receive the updates, AC got its grids unload thing hang in the air (#646, https://github.com/azerothcore/azerothcore-wotlk/commit/2779833768bbe9967006d6d16888dace05b4bcb6, https://github.com/azerothcore/azerothcore-wotlk/pull/17480). TC should be ok.

**Comment by infidelus** [comment]
Having not played for a while I tried compiling TC the other day and ran across this problem.  If I'm reading @trickerer's reply correctly this should be fine on AC but TC cannot be built?  Or am I missing something obvious as I cannot see any updates for TC?

I generally use a script to automate the build which pulls the patch from https://raw.githubusercontent.com/trickerer/Trinity-Bots/master/NPCBots.patch.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/5da5b7193a8f79587e9db44b5a589d45278162e6
