### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] ISSUE_TITLE

### ISSUE THREAD

**Issue by alexyang-sea** [trickerer/Trinity-Bots#657]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I want to merge NPCBots into zhengpeiru21's playerbot's core by copying NPCBots.patch under AC in NPCBots to azerothcore-wotlk and using patch -p1 < NPCBots.patch command, but after VS2022 compilation there are 2 Error:

D:\AzerothCore\git_Core\zhengpeiru21\azerothcore-wotlk\src\server\game\Entities\Player\PlayerUpdates.cpp(470,21): error C2065. "p_time": undeclared identifier
2, D:\AzerothCore\git_Core\zhengpeiru21\azerothcore-wotlk\modules\mod-playerbots\src\ PlayerbotFactory.cpp(558,48): warning C4834: Discard the return value of functions with the "nodiscard" attribute
May I know how to compile NPCBots with Playerbot under windows?

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
I never tried that myself.
I don't track playerbots module updates but I know it uses its own modified core which creates a high chance for code conflicts. If you didn't get any errors during patching then you should be good for that phase of combining bots codebases, now it is up to you to fix any compilation errors you get and hope you don't get any crashes when you run the server due to functionality compatibility issues.

**Comment by evrydayjunglist** [comment]
Curious if you figure this out, please share. I'm trying to see if I can get VS to compile, but I don't expect to be successful.
