### ISSUE TITLE
[TC] [Bug] [Core] NPCBot's pets are aggressive to owner and party members at all times when world PVP set to FFA

### ISSUE THREAD

**Issue by Codewow** [trickerer/Trinity-Bots#660]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When world PVP settings are set to FFA, NPCBOT pets are all marked aggressive to the owner of the bots as well as anyone around them, even when in a party.

### Expected behaviour

Bot pets should be friendly and not take damage from owner when PVP is FFA, in or out of a party.

### Steps to reproduce the problem

1. Enable FFA PVP in world settings
2. Purchase a bot of a class that has a pet.
3. Notice pet is hostile to you

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. ef4f8ac18b4d 2023-07-21 21:33:30 +0000 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Windows 10

**Comment by trickerer** [comment]
The problem is caused by player control flag on pets. You can't attack it since it is in fact friendly, but in FFAPVP mode client assumes player-controlled unit is an enemy unless said player is in party or some other form of forced reaction. The only problem is that **player** owner of bot's pet is impossible to find.
Disabled player-control flag on pets for now. And on totems too, I saw player not getting buffs from say mana spring totem casted by shaman bot.
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/26d0c7199f8818fb043e8e8c068cfd0543647850

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/dd5e5cf59b39d8254edbf1417a5166251eaa9547
