### ISSUE TITLE
[TC] [Crash] [Core] Worldserve crash

### ISSUE THREAD

**Issue by 0775123** [trickerer/Trinity-Bots#662]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Call stack:
Address   Frame     Function      SourceFile
0000013F7000B000  000000000013F200  0000:0000000000000000 
0000000140149225  000000000013F3C0  `BotMgr::_teleportBot'::`2'::<lambda_1>::operator()+A5  E:\TrinityCore\TrinityCore-Bots\src\server\game\AI\NpcBots\botmgr.cpp line 1248
000000014014DF1F  000000000013F3F0  BotMgr::HandleDelayedTeleports+2F  E:\TrinityCore\TrinityCore-Bots\src\server\game\AI\NpcBots\botmgr.cpp line 2812
000000013FCB43C3  000000000013F420  MapManager::Update+B3  E:\TrinityCore\TrinityCore-Bot\src\server\game\Maps\MapManager.cpp line 246

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. fa62554f2433 2023-10-16 10:54:13 +0800  (Win64, RelWithDebInfo, Static)

### Operating system

Win10

**Comment by trickerer** [comment]
Please upload a debug crashlog to https://gist.github.com

**Comment by Miying1** [comment]
> * fa62554f2433 is not a TC commit revision
> * Please upload a debug crashlog to https://gist.github.com

https://gist.github.com/Miying1/2a3893af51af71eaf5f4d2396b8ff43f#file-34dc74270aa8-_worldserver-exe_-26-10_12-3-9-txt

**Comment by trickerer** [comment]
- [34dc74270aa8](https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/34dc74270aa8) isn't a TC revision either, let alone your custom changes I cannot guess what they are
- Crashlog points to botmgr.cpp line 1254 which is a single curvy bracket following a simple pointer comparison - crash couldn't happen at that location. Since I cannot know what version of bots you're using this info isn't helpful at all
- You posted a RelWithDebInfo crashlog, which doesn't contain enough debug info to guess the crash reason and location, 'debug crashlog' request wasn't a mere suggestion
