### ISSUE TITLE
[TC] [AC] [Question] How can I get more female bots??

### ISSUE THREAD

**Issue by GesiIvy128** [trickerer/Trinity-Bots#668]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hello! Your project is amazing! Forgive me, this is my second question in a day:

I hope to have more female bots. I found an issue requesting a command to change gender. https://github.com/trickerer/Trinity-Bots/issues/619#issue-1873259296

Actually, I don't need you to develop that feature specifically. I have some database and LUA script knowledge, and what I want to ask is: **Is it possible for me to customize the gender and appearance of those NPC bots myself?**

In the ALL_world.sql file, I noticed that you've created the `creature_template_npcbot_appearance` table, which contains the `gender` for each bot. There's also a `gender` in the `creature_template_outfits` table. Additionally, in some other tables, there's a `modelid1` variable, which I understand controls NPC appearances. So, would changing these `gender` and `modelid1` values allow me to change the gender and appearance of the bots (after a server restart)? 

Do you have more detailed advice?

I really want more female bots. For example, in the current templates, all the Alliance druid bots (which, of course, can only be Night Elves) are male! There are no female ones! This seems a bit unreasonable.

### TrinityCore or AzerothCore

Both

**Comment by trickerer** [comment]
Well, first of all leave `creature_template_outfits` table out - it doesn't contain any data for standard classes.

Yes, you need to change `modelid1` in `creature_template` table to some valid model id of an opposite gender for that bot's race.
Then you have to also change bot's `gender` in `creature_template_npcbot_appearance` table.
And finally you'll need to manually correct all possible value overflows for new race/gender combination appearance details, as was mentioned in [#619 (comment)](https://github.com/trickerer/Trinity-Bots/issues/619#issuecomment-1703653746).
I'm pretty sure you will also want to change their name, eh? Client cache purge is required in that case.

Be aware of the fact that I didn't do an intentional gender change of a bot like this myself, I only had to fix some nasty mistakes in bots generation.

As for why bot roster is what it is: all but few bots of standard classes were created based on existing class trainers, look at the names (!), guess what - all Night Elf Druid trainers are male.

**Comment by GesiIvy128** [comment]
Here's my custom for today:

I made three table modifications for the Paladin bot with `entry`=70061:

1. In `creature_template_npcbot_extras`, I changed the `race` to 4 (Night Elf).
2. In `creature_template_npcbot_appearance`, I switched the `gender` to 1 (female).
3. In `creature_template`, I updated `modelid1` to 9551 (a female Night Elf NPC from Darkshore).

After clearing the cache and restarting the server, voila! I've got a **female, Night Elf, Paladin**!

_I can hardly resist sharing this message with the brother from #619, lol~_

**Comment by GesiIvy128** [comment]
The bad news is that the bug I discovered in the final part of #667 still persists. When I set NpcBot.Transmog.UseEquipmentSlots to 1, the appearances of all the weapons and shields on the bot vanish. All the robots are fighting bare-handed.

**Comment by trickerer** [comment]
About the transmog issue. I couldn't reproduce it, so please open a new issue with exact steps to reproduce it.
