### ISSUE TITLE
 [AC] [Question] [Core] can not understand some code, thanks

### ISSUE THREAD

**Issue by SouthMemory** [trickerer/Trinity-Bots#673]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description
[code here](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/blob/de00b639b3247098cf809ac038b227181443fa06/src/server/game/Entities/Creature/Creature.cpp#L1863C11-L1863C11)

what's the use of  line 1866:
`       
if (sWorld->GetMaxPlayerCount() > 0)
    return false;
`

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
When grid is loaded all creature spawn locations within it get activated (creatures get spawned). This also happens when bot is forcefully spawned at server startup - first bot spawned within grid automatically activates all surrounding creature (including bots) spawn locations (loads own grid).
If creature is NPCBot, in case of an error in map related code logic, creature may get loaded twice which will cause undefined behavior in bot code. For example grid containing owned bot may get unloaded.
Code in question refers to server's current run statistics - max players here means 'max recorded count of players online'. If this count > 0 then somebody has already logged in and no bots should be spawned by grid activation. It's a very old piece of code - it could probably be replaced with AllBotsLoaded() check.

Overall I cannot tell if this code is redundant by now or not.

**Comment by SouthMemory** [comment]
There are some code that needs a change, because they would cause "ACCESS VIOLATION" on windows
As I don't know how to make a pull quest, I'll post it here:
1.bot_ai.cpp
**original**
  if (botPet)
      botPet->GetBotPetAI()->ResetAuraUpdateMaskForRaid();
**New**
  if (botPet && botPet->GetBotPetAI())
      botPet->GetBotPetAI()->ResetAuraUpdateMaskForRaid();

2.bot_death_knight_ai.cpp
if (botPet)
    botPet->ToTempSummon()->UnSummon();

just the same

maybe could be of some help.

**Comment by trickerer** [comment]
> There are some code that needs a change, because they would cause "ACCESS VIOLATION" on windows

Make a proper crash report and don't mix issues please
