### ISSUE TITLE
[AC] [Crash] [Core] Random Crash Occured By Random Moments

### ISSUE THREAD

**Issue by jakatangkir** [trickerer/Trinity-Bots#705]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Worldserver is crashing in random moments, for example that got caught on my attention:
- Players opening item Curious Crate
- Players doing dungeon
- Doing Profession(?)

There is lot of things that may caused this that i didnt notice because i was away cannot pay attention to the server.

Please notice, i use the lastest version on the AC patched npcbot github. and the version is shown 00000

Also before applying new version of core on lastest github, i got this error too:
https://gist.github.com/jakatangkir/ef34ca7a8de11d3cc2d63747bd214c14

i would say thank you before, for creating us this

### Expected behaviour

At some condition this should not occur tho, i tried to also fresh install npcbot manually by patch it got lots of error. so cant tell if the problem comming from AC itself?

### Crashlog

https://gist.github.com/jakatangkir/0a0023660fcac67f4b7481b5ed9434f0

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release, Static)

### Operating system

Windows Server 2016 (12GB RAM 4Core)

**Comment by trickerer** [comment]
https://gist.github.com/jakatangkir/ef34ca7a8de11d3cc2d63747bd214c14: this crash is caused by SmartAI action trigger infinite loop via `Creature::CallForHelp()` (probably 2+ creatures triggering each other), so this is purely AC problem. I had something like that happening in Shattered Halls, but it was some caster instantly summoning a creature that engaged and called for help triggering the same caster to summon again.

https://gist.github.com/jakatangkir/0a0023660fcac67f4b7481b5ed9434f0: this crashlog was created under Release build - an optimized build so call stack points to semi-random locations, it's impossible to tell what happened.

**Comment by jakatangkir** [comment]
Thank you for your response, sorry for my late response. So is there any way that the AC with npcbot will be updated to newest AC? I tried to apply it manualy, but seems some patch settings does not applicable to new AC.
It is more buggy i guess, https://gist.github.com/jakatangkir/ff2199ded46d56d5ac72d88ac8a54486

On my first version of AC with npcbot also crashes with the error STACK_OVERFLOW, so i did update to the newest git, seems the issue doesnt end just there xd

**Comment by trickerer** [comment]
https://gist.github.com/jakatangkir/ff2199ded46d56d5ac72d88ac8a54486 crash here happens during normal creature's waypoint movement intitialization but that's not a well known code for me so I can't tell what could cause that error, all I can say is that this code is not related to bots. First though was that the culprit is recent movement-related PR but it wasn't merged yet https://github.com/azerothcore/azerothcore-wotlk/pull/18013.

Unfortunatelly there is no estimate on the next stable patch release. One day I'll be able to work my C++ projects again and bots patch will be the first on my list.

**Comment by jakatangkir** [comment]
Thank you for the explanation, i am really grateful and thankful for any of your projects.
While waiting i'll keep looking for ways to fix any issue making the server crash unexpectedly

**Comment by jakatangkir** [comment]
In anyway, is the visual studio version also effect on final compiled version? 
Or is it also effect on any version of cmake, boost and more?

**Comment by trickerer** [comment]
The short answer is: no. If compiler or boost version isn't listed as supported, you're way more likely to get an error during cmake project generation or compilation, the app may also crash at startup with garbage crashlog, maybe even before server fully initializes.
If you get a crash the reason is code error 99.99% of the time.

**Comment by jakatangkir** [comment]
Hello, just want to report here again instead of making a new issue and want to know the crash's cause. because I almost got the same fault address error.
i assume it has something to do with the combat state? and also smartAI?
https://gist.github.com/jakatangkir/ef8d6552e36f8b08802baa4333630330
Thank you

**Comment by trickerer** [comment]
> Hello, just want to report here again instead of making a new issue and want to know the crash's cause. because I almost got the same fault address error. i assume it has something to do with the combat state? and also smartAI? https://gist.github.com/jakatangkir/ef8d6552e36f8b08802baa4333630330 Thank you

Same as previous SmartAI related call stack overflow crash https://gist.github.com/jakatangkir/ef34ca7a8de11d3cc2d63747bd214c14

**Comment by jakatangkir** [comment]
i seen a post on AC that somehow changing the stack size fix the issue, tried it via cmake command setting it to 16MB hope it fix it

**Comment by jakatangkir** [comment]
Update, seems the stack overflow crash didnot occured. and i switch version to RelWithDebInfo version, and this might be a crash that seems have relation with npc bot? just informing.
https://gist.github.com/jakatangkir/467fedf1f7cb09c006a5a87c060d7d91
