### ISSUE TITLE
[AC] [Crash]ASSERTION FAILED

### ISSUE THREAD

**Issue by lemonmomomo** [trickerer/Trinity-Bots#709]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

# Location 'E:\ac335\AzerothCore-wotlk\src\server\game\AI\NpcBots\botmgr.cpp:1492'
# Function 'BotMgr::AddBot'
# Condition 'bot->IsNPCBot()'
https://gist.github.com/ This website is really difficult to connect to in our area!This is my first upload and took me a long time to study. Please forgive me!

### Expected behaviour

My brother was playing yesterday, and he couldn’t explain what he did, and I don’t know how to recreate it!

### Crashlog

https://gist.github.com/lemonmomomo/8305fb2ad3d1edaba4bd7804bebc716a

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. de00b639b324+ 2023-10-22 07:59:05 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

win10

**Comment by trickerer** [comment]
Well, because of `RelWithDebInfo` all I can tell is creature in question has npcbot name and is not a npcbot at the time of hire attempt through botgiver, but has bot AI initialized.
Try to find your Crypt Lord `Horus'aman` and try to hire them directly, if you get the same assertion then you missed some bot update SQLs, you may even be unable to see bot's model.
Otherwise it's not impossible that bot got removed from world. In that case update to latest AC+bots repo version. Don't forget to back up your DBs - latest build isn't tested.

**Comment by lemonmomomo** [comment]
Crypt Lord Horus'aman...Yes, that's it, I tried hiring it again and the same assertion actually appeared.
I saw your version 7 hours ago. I will try it after updating tomorrow. Thank you very much!

**Comment by DykeRz** [comment]
just reinstall

**Comment by lemonmomomo** [comment]
@trickerer @DykeRz  Thank you!
 
There is something wrong with my database!
I haven't modified anything in this data, I just made some localization additions to some local tables, but I confirmed that Crypt Lord was normal when it was added at the beginning, because I added it on the map.
I also checked the updates between the 2023_05_20_00_creature_template.sql and 2023_08_13_00_creature_template_npcbot_appearance.sql tables and found nothing missing!I don’t know when I was defined as a non-NPCbot.
 It’s really a magical thing.But I updated them anyway, and when I entered the game again, the Crypt Lord character could be hired normally.
