### ISSUE TITLE
[AC] [Question] [Core] Making a custom maxnpcbot value

### ISSUE THREAD

**Issue by jakatangkir** [trickerer/Trinity-Bots#712]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hello, i wanted to ask a bit.
I wanted to make a custom maximum value on renting npc bot by their account id.
 -code removed
i am currently only editing the botmgr.cpp, do you think this will work in any way? thank you for your time.

### TrinityCore or AzerothCore

AzerothCore

### Operating system

Win Server 2016

**Comment by trickerer** [comment]
Not going to discuss presented code.

Per-account bot limit is doable, in theory. But you need a way to select all bots from `characters_npcbot` table owner by account id instead of player id. Otherwise it can be done pretty simply - all existing limiting factors are being checked in `BotMgr::AddBot()`, just add your own

**Comment by jakatangkir** [comment]
thank you for the additional info, it is really saves time
