### ISSUE TITLE
[AC] [Bug] [Spell] Windfury non handled item enchantment

### ISSUE THREAD

**Issue by Day36512** [trickerer/Trinity-Bots#775]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Been getting a regular worldserver error of Unit::HandleDummyAuraProc (bot): non handled item enchantment (rank?) 0 for spell id 33757 (Windfury)

Not sure where to check on this one for a fix. Started happening when you came back to implement weekly merges so maybe it's something implemented from acore. Been attempting to resolve on my own as I'm uncertain if it's from a personal change or not.

### TrinityCore or AzerothCore

Azerothcore

### Core rev. hash/commit

AzerothCore rev. abc4d5a86523+ 2024-04-06 03:35:05 -0600 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Win 10

**Comment by trickerer** [comment]
I checked all ranks but never triggered this error for neither bot nor player.
The error says that item used as proc source exits but is unenchanted (temporary slot enchant id 0), temporary enchant slot is of course for timed enchants. Possibly spell was triggered by an aura applied directly to unit and not weapon enchant? Or maybe it was a different enchant slot.

What I noticed though is that Windfury proc was broken completely. Not only it was rolling proc chance a second time, but also a cooldown was multiplied by 1000 which seems a regression - base was changed at some point - so instead of 3 seconds it was 50 minutes. Ouch.
Looks like this dummy proc was changed some time ago and I didn't notice, well I'll sync bot code there asap.

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/bd74f4daa4fef6c8cf6e8249dbcb18e2e9a083b0

**Comment by Day36512** [comment]
Thank you!

**Comment by Day36512** [comment]
Issue seemms to persist with same error message.

**Comment by trickerer** [comment]
Yes, the fix unrelated to your problem. I've already made my assumptions above.
At this point the only way to find the source is to debug on your end, just set a breakpoint at that error message in Unit.cpp and check the call stack to find out why castItem is there but unenchanted properly and what the items is.
