### ISSUE TITLE
[AC] [Bug] [Core/SmartAI] Death Events Where target = Invoker does not trigger if bot is killer

### ISSUE THREAD

**Issue by Day36512** [trickerer/Trinity-Bots#782]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Death events where target is invoker in smart ai will not trigger on bots, at least with SmartAI.

To replicate:
1. Spawn Warlord Krom'zar, id 9456
2. Kill it yourself without bots
3. Banner will appear

However when bots are the killer, banner will not appear. 

I changed target to self for further testing and the banner appeared even when bots killed him, so must be something with action invoker.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. b49c8d6c41e0+ 2024-04-19 21:54:23 -0600 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Win10

**Comment by trickerer** [comment]
This problem is caused by target selector vs spell range and is reproducible with no bots.
Spell 13965 has spell range of 5yd yet related smart script uses target_type 7 (SMART_TARGET_ACTION_INVOKER), so the action fails without even trying to cast unless killer is within melee range (killed unit tries to move towards the target instead as per standard smart script logic). Reproducible by just killing the creature from a distance. Also spellinfo target is TARGET_DEST_CASTER.
So it's just a poorly composed smart_scripts table entry.

https://github.com/trickerer/Trinity-Bots/assets/1254989/941946f3-38a5-43c4-a22f-404b05fa3405
