### ISSUE TITLE
[TC] [AC] [Feature] [Group/Core] Suggestion on using the revive NPCbots command only when the player is alive

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#800]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Usually, players can execute the command to revive NPCbots through the speaking channel while in survival mode.
After the player dies, the default speaking channel can no longer execute the command to revive NPCbots.
But players can execute the command to revive NPCbots by switching between teams or guild channels.
Then, in the game, players appear to be in a dead state, repeatedly entering commands to revive NPCbots, and finally lying on the corpse wins the boss.

To ensure the playability and fairness of the game, please consider limiting the execution of revive NPCbots commands.
After the player dies, it is necessary to prohibit any dialogue channels from entering commands to revive NPCbots.

### TrinityCore or AzerothCore

Both

### Core rev. hash/commit

AzerothCore-wotlk-with-NPCBots 9431a06  2024-05-14

### Operating system

Ubuntu 18.04

**Comment by trickerer** [comment]
I have to remind you that `.npcbot revive` is a GM command and isn't supposed to be used by players, ever. Did you give this permission to your players then?

**Comment by moncat2005** [comment]
Yes, in order for players to revive NPCbots through the NetherBot addon, I have lowered this resurrection command to player level 0.

**Comment by trickerer** [comment]
Sorry but I can't be fixing issues you create with your own hands. Revive command was never supposed to be available to players, once bot dies it can only revive after a certain amount of time player spends out of combat.

**Comment by moncat2005** [comment]
Okay, I will carefully adjust the level of each command according to the command instructions in "THE NPCBOTS MANUAL".
Adjust all execution restrictions except for player command to level 1 and level 3.
However, during the verification process, I found that some of the commands in the instructions were missing from the command table in the database, such as:
. npcbot useonbot spell [Resurrection]
. npcbot useonbot spell Dampen Magic
. npcbot useonbot spell intervene
. npcbot useonbot item [Gnomish Army Knife]
. npcb use s Intervene
. npcbot go
. npcbot wp

Have these commands not been implemented yet?

[NPCBOT-COMMAND-SECURITY.TXT](https://github.com/trickerer/Trinity-Bots/files/15362929/NPCBOT-COMMAND-SECURITY.TXT)

**Comment by trickerer** [comment]
All these command were implemented.
At some point `.npcbot ...` commands were removed from `command` table, for several reasons:
- `command` table is mainly used to provide help messages you see when you invoke `.help ...` while help messages are already included in code and `command` table has no localization counterpart. Altering security level generates a warning
- missing `command` table entry message log level was debug and not error (not sure what it is now)
- updating the table every time you make a change in some command or add one seems a wasted effort especially during active development, especially because it creates more sql files
- for TC npcbot commands and their permissions are already listed in permissions tables

I think missing command message log level is now error, need to check it. If so `command` table will need to be populated with npcbot commands again

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/6de48a959511286e5cc582bbaeda8f170ebfcee9
