### ISSUE TITLE
[AC] [Question/Feature] [Core] creature_template_locale.sql,How to display Chinese in the previous generation

### ISSUE THREAD

**Issue by saliven1970** [trickerer/Trinity-Bots#801]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

creature_template_locale.sql,How to display Chinese in the previous generation？Chinese will be displayed when they are away from the role, and English will be displayed when they are near.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 2031358c01a4 2024-05-18 14:09:35 +0700 (master branch)

### Operating system

OpenEuler22.03

**Comment by trickerer** [comment]
This translation is horrible.
All I can suggest is deleting client's cache. If problem persists provide some screenshots please.

**Comment by saliven1970** [comment]
![未标题-1](https://github.com/trickerer/Trinity-Bots/assets/37821954/30b5d607-8b51-44f6-9d8c-8a354139f5ed)
I have deleting client's cache. and this is a screenshots.
When NPCBots around the character,English will be displayed,and The name of another NPCBots in the team is displayed in Chinese because they is far away.

**Comment by saliven1970** [comment]
![未标题-2](https://github.com/trickerer/Trinity-Bots/assets/37821954/ef431e70-6dbe-4bb8-8ac7-d6404bd2152d)
We approached these NPCBots, and their names were displayed in English.

**Comment by saliven1970** [comment]
These are all previous NPCBots, and the new ones will always display Chinese.

**Comment by trickerer** [comment]
Well, can't confirm.
I added two entries in creature_template_locale, one with name and subname (reshly spawned), one with name only (owned for a while). Upon clearing cache both bots got translated names in group, close and far range, one bot got only its name translated, another got both name and subname translated. Maybe some addon does that on your side?

The only real problem I notice is that in group join/leave/create/disband client messages supposedly localized bot names were displayed both translated and original from time to time. That's because group updates only send GUIDs so client has to rely on its own *creature* names cache while group update packet is supposed to only contain player GUIDs. I can't do anything here.

![names](https://github.com/trickerer/Trinity-Bots/assets/1254989/6f5e1d89-2b9a-4e9c-8a16-2ae63f7dd3cb)
