### ISSUE TITLE
improvement - Mage does not use Mirror Image

### ISSUE THREAD

**Issue by Ryu1254** [trickerer/Trinity-Bots#81]
can you implement Mirror Image for Mage in the rotation. I notice this ability does not exist for Mage bot.
this could improve a lot of DPS and would benefice from 4 piece of T10 gear bonus.

**Comment by trickerer** [comment]
The problem here is the way mirror image spell cloning works. It's kind of buggy and not fully functional, for example if mirror image is polymorphed it will lose its displayId.

I did some testing, seems like MI summoned by creatures can only have their base model displayed regardless of sent MI packets (could be related to applied clone auras).

**Comment by Ryu1254** [comment]
Ok.. what if we don’t care the display model ID. We force to use one?
Will that work?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by trickerer** [comment]
Mirror Image spell already forces a model ID, and after that MI packets are sent on player request.
For creatures these packets are ignored though, not sure why.

Pausing on that for now.
