### ISSUE TITLE
[TC] [AC] [Bug/Crash] [Group/Spell/Core] SQL Error (1054): Unknown column 'modelid1' in 'field list'

### ISSUE THREAD

**Issue by ToneCre8** [trickerer/Trinity-Bots#858]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Can't apply SQL updates to world database.
SQL Error (1054): Unknown column 'modelid1' in 'field list'

### Expected behaviour

Update should succeed.

### Steps to reproduce the problem

Build latest pre-patched AzerothCore-wotlk-with-NPCBots 
Attempt to update sql with scripts located in Trinity-Bots-master\AC\SQL.

Bot NPC's don't appear in game.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 3d00d05f4972 2024-08-09 21:27:36 +0000 (npcbots_3.3.5 branch)

### Operating system

Debian 12

**Comment by trickerer** [comment]
If you build pre-patched AC repo you don't need to apply any additional SQLs to your DBs, given DB autoupdate is enabled (default).

NPCBots don't appear in the game because you have to spawn them manually

**Comment by ToneCre8** [comment]
Thank you Trickerer! 

And if I choose to patch myself do I then need to apply the updates in AC/sql from the repo?

**Comment by trickerer** [comment]
> Thank you Trickerer!
> 
> And if I choose to patch myself do I then need to apply the updates in AC/sql from the repo?

If you apply the patch before running the server for the first time then you don't need to do anything - your DBs will be created automatically and all npcbot tables along with it.

If databases already exist then you'll have to manually execute npcbot 'base' SQLs, and when you launch the server again it will automatically install all the updates. Since the set of files needed to be executed may change eventually here is a general approach (AzerothCore):
- Open AC patch file and look at the list of files it creates (in patch summary)
- Look for lines starting with 'create mode 100644 data/sql/**base**/...'. Currently they are:
  - data/sql/base/db_characters/characters_npcbot.sql
  - data/sql/base/db_characters/characters_npcbot_group_member.sql
  - data/sql/base/db_characters/characters_npcbot_stats.sql
  - data/sql/base/db_characters/characters_npcbot_transmog.sql
  - data/sql/base/db_world/creature_template_npcbot_appearance.sql
  - data/sql/base/db_world/creature_template_npcbot_extras.sql
  - data/sql/base/db_world/creature_template_outfits.sql
- Apply those to their respective DBs, here 4 go into `acore_characters` and 3 into `acore_world`, apply in the same order they are listed

If you've already tried to launch the server after patching and got a crash via SQL error it shouldn't affect anything

**Comment by Wimmetje1** [comment]
> If you build pre-patched AC repo you don't need to apply any additional SQLs to your DBs, given DB autoupdate is enabled (default).
> 
> NPCBots don't appear in the game because you have to spawn them manually

just to be sure, if i install your wotlk npcbots fork i don't have to inject separate sql files? because it was described that way in the installation manual?

**Comment by ToneCre8** [comment]
That is correct. I was a bit confused too while trying to follow the instructions. But if you build from the fork, you do not need to do any of the sql updates.

**Comment by trickerer** [comment]
> > If you build pre-patched AC repo you don't need to apply any additional SQLs to your DBs, given DB autoupdate is enabled (default).
> > NPCBots don't appear in the game because you have to spawn them manually
> 
> Just to be sure, if i install/compile your wotlk npcbots fork i don't have to inject separate sql files? Because it was described that way in the installation manual? Or is that only for trinitycore?

If you do a fresh AC install you don't need to do anything with SQL files manually
