### ISSUE TITLE
[TC] [Crash] [Core] Sharing fixes

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#864]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

In latest update i got some crashes, this is some fixes what i did

Installed mods:
Autobalance for NPCBots, transmog legion (Rochet), player time reward, Demon Hunter class and some little changes

[log2024-08-21-14-04-27.log](https://github.com/user-attachments/files/16695979/log2024-08-21-14-04-27.log)

[log2024-08-21-16-56-28.log](https://github.com/user-attachments/files/16695983/log2024-08-21-16-56-28.log)

![crash1](https://github.com/user-attachments/assets/a48520af-ac0d-46f5-836a-b6f4c8df2821)
![crash2](https://github.com/user-attachments/assets/78433a85-efbb-49df-a174-2ebadc0434b8)

if it would be useful

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

latest

### Operating system

debian 12

**Comment by trickerer** [comment]
Thanks but only this is a pretty terrible hackfix, but also I don't really want to integrate a fix from a heavily modified core without knowing exactly what caused the issue. The transport-related crash could be kind of interesting to look into but again - there is no way to tell the reason behind it without a debug crashlog. That's why issue template exists.
Considering the above, closing now
