### ISSUE TITLE
[AC] [Question] [Spell/Core] Tallents used by Spec

### ISSUE THREAD

**Issue by Bogir** [trickerer/Trinity-Bots#865]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

1. How can I find out what talents are used by a bot in a specific specialization?
2. Does the bot use symbols depending on the spec?

1. Как можно узнать какие таланты задействованы ботом в конкретной специализации?
2. Использует ли бот символы в зависимости от спека?

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
Both questions were answered several times now, nothing has changed since then. You can't really see what talents or glyphs bot uses aside from looking into the source code, many glyphs and talents had to be carefully scripted for bots in order to make them work so /bonk is not always the answer. The general approach for both explained here:
1. https://github.com/trickerer/Trinity-Bots/issues/138, https://github.com/trickerer/Trinity-Bots/discussions/370
2. https://github.com/trickerer/Trinity-Bots/issues/38#issuecomment-720887253, https://github.com/trickerer/Trinity-Bots/issues/690#issuecomment-1817822432
