### ISSUE TITLE
[TC] Question] [Core] Cannot Run Auth SQL Permissions Files.

### ISSUE THREAD

**Issue by Brian-Hopkins** [trickerer/Trinity-Bots#877]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I am using heidisql and trying to run the SQL files in the updates auth folder. I keep getting a  SQL Error (1812) : Tablespace is missing for table 'auth','rbac_ ****'. for each of these auth SQLs. Am I missing something here?

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. f9881fe6bdbe 2024-09-14 15:23:19 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Windows 11

**Comment by trickerer** [comment]
This isn't a bots issue.
Such error means SQL server is unable to write data to disk. In your `C:/ProgramData/MySQL/MySQL Server X.Y/Data/auth/` rbac_permissions.ibd and other RBAC table files are either missing, corrupted or lack write permisson.
Have you migrated your server recently? Updated to a new version of MySQL Server? If so you can just move old DB files to a new location. Otherwise just google this error, I'm not really the guy to ask for a solution of a problem like that.
