### ISSUE TITLE
[AC] [Bug] [Equipment] NPCBots can equip multiple Unique items at the same time.

### ISSUE THREAD

**Issue by Badgermilk0** [trickerer/Trinity-Bots#915]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Currently NPCBots can equip more then 1 unique items, ex. 2 Bloodclot Band Rings at the same time.

![image](https://github.com/user-attachments/assets/1fc6edeb-e07c-47cb-9046-4db49b858abe)

### Expected behaviour

Not being able to use more then one of the same Unique Item at the same time.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. dca2df72439d 2024-10-26 05:40:12 +0700 (npcbots_3.3.5 branch)

### Operating system

Win 11

**Comment by Bogir** [comment]
in addition, the bot ignores almost all checks for wearing or using items, stones for sockets or improvements that are required by a regular character.
I think this is a big plus. The main thing for you is to control these moments and use them to compensate for some unfinished spells or abilities of bots.

**Comment by trickerer** [comment]
That's intended. Bots don't need to follow **every** player rule. That' not a big deal and to prove it this is the only report pointing that out as a problem in 10 years.
Now, the reason that's intended is because if bot can't equip an item it just won't show in the repective menu. And if player forgets what bot has equipped it may take them quite some time to figure out that the problem is item's unique / unique-equipped status. In case of unique gems it's even worse. I don't want to frustrate players with such revelations so bot will just grab the item. ~~Stuff 'em full of Dragon's Eyes~~.
Bots will also ignore skill requirements (ring enchantments, etc.) and race restrictions. Fury Warrior bots are also able to Titan Grip some weapon types players cannot.
