### ISSUE TITLE
[AC] [Feature] [Core] Enhancement suggestions for gearbank in NPCBOTS

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#923]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

The equipment in the current list can display GS, but it is not sorted in descending order according to GS value.
In addition, from the perspective of players, it is best for gearbank to be able to classify and sort equipment based on their type, making it easier for players to choose equipment for different NPCBots professions.
For example, based on categories such as head, shoulders, chest, waist, hands, pants, shoes, etc., achieve graded arrangement.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore-wotlk-with-NPCBots 03bdf64  2024-11-09

### Operating system

Ubuntu 22.04

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/da3fbac3d83452537938ad0ad9fcddc57ba80a2a

You can't really sort by GS as it's class dependent, so item class / subclass / inventory type take priority.

I'm not adding sort type selection - it requires complexity raise to the level of auctionhouse, sort predicate is tied to the stl container type so it requires keeping and synchonizing several different containers.

**Comment by moncat2005** [comment]
Great, thank you very much.
Questions under testing:
1. Does equipment set refer to real kit equipment or ordinary equipment integrated equipment?
2. Does' MISSING' in NPC_TEXT  refer to the display of failed equipment applications or missing components?

**Comment by trickerer** [comment]
This machine translation could be interpreted quite a few different ways so I'll just try to explain.

1) Equipment set is a set of item IDs that were equipped on a bot at the moment the set was created. Standard (visual only) items are automatically ignored.
2) In set item listing menu (when your click on set name) missing items are diplayed with `swords` icon (crossed kind of). When you clink on such item bot will say that the item is missing. If you try to equip bot with a set containing missing items the error will mention exactly this. Now word `missing` here refers to items *not found in gear bank* - to use a set all its items must be stored within gear bank, not player bags

If bot fails to equip a set due to some reason other than missing items this will be shown in error message instead of `missing` in format `Failed <error_core> (<slot>)`

<details><summary>Dang it</summary>
<p>

I completely forgot to document this

</p>
</details>
