### ISSUE TITLE
[AC] [Bug] [Core] About npcbot command unbind issue

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#936]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

After the player executes the NPCBOT command unbind, the NPCBOT disappears, but the equipment cannot be returned from the mailbox.
At this point, when you go to the NPC of the employment agency, it shows that the quantity is full and you cannot continue to hire.
This issue usually returns to normal after the WorldServer is restarted.

I am somewhat confused about the result of executing this command response.

### Expected behaviour

After executing the unbind command, it should take effect as soon as possible.
And handle the equipment return action from the mailbox for the fired NPCBOT.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 3e2db3e 2024-11-22 16:29:23 +0800 (npcbots_3.35 branch) 

### Operating system

ubuntu 22.04

**Comment by trickerer** [comment]
This is the intended behavior. `.npcbot unbind` command tells the bot to not participate in player acitivities temporarily, it doesn't fire the bot.
> unbind <_TARGET_|_NAMES..._> -- free NPCBot(s) temporarily without dismissing them. Bot(s) will return to home position and wait there until invited back (or server restart)

Executing `.npcbot unbind` is not the same as clicking dismiss option in bot gossip menu.
This command '**effectively** (not literally) suspends bot ownership temporarily', not 'literally fires the bot'. Since player's ability to hire new bots is based on the number of owned bots, not on the number of currently active bots - player can only have `NpcBot.MaxBots` bots regardless of their active state. And since the bot isn't fired there is no reason to return the gear.
It's not like player has to only pay once for each bot (per id) and then they're able to fire and hire the same bot again without paying

**Comment by moncat2005** [comment]
After executing the command:. npcbot unbind, the NPC should return to the spawn point.
How to recall an NPC when it cannot be seen?

**Comment by trickerer** [comment]
> After executing the command:. npcbot unbind, the NPC should return to the spawn point. How to recall an NPC when it cannot be seen?

`.npcbot command rebind`
Check Readme to see all commands

**Comment by trickerer** [comment]
Is this a problem? I mean not only this is unrelared to the original post, but also what do you want me to do about that, improve your players' memory?
Ask your addon developer is you want something like unbound bots list in dropdown menu or separate window or anything addon related really, maybe they will be able to help you.

**Comment by moncat2005** [comment]
no problem.
