### ISSUE TITLE
[AC] [Question] [Group] Thanks

### ISSUE THREAD

**Issue by Conan1996-2** [trickerer/Trinity-Bots#937]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

This is not an issue, but more of a public thank you for all the hard work you do on this endeavor. I mainly use this for BGs and the occasional dungeon, so the new BG that was implemented was a huge + for me, and I cant wait to see more BGs done.

Should I map out another BG or just leave it to you? I just know how much time it takes to do.

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
> Should I map out another BG or just leave it to you? I just know how much time it takes to do.

There is no need to. In fact I doubt I will be implementing another BG any time soon since I enountered a number of roadblocks while trying to figure the remaining 2 BGs out. One is that bots need to be able to carry and use an item, another thing is that bots need to be able to control a vehicle on their own and that's a big one, a third is the destructibles blocking access to certain WPs (gates). But the main problem is of course the fact that neither of those BGs are working 100% on TC, this pretty much stops me from even trying since I certainly want bots to work the same for both cores.
