### ISSUE TITLE
[Question] Target NPCBots with Player Specific Spells and Abilities

### ISSUE THREAD

**Issue by Badgermilk0** [trickerer/Trinity-Bots#944]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

This is a recurring question I've noticed over the years.

I remember reading that the last time you had the NPCbots as valid targets for Player Only boss spells it came with instability.

Is it possible to examine this again if anything has changed?

Or does this need to be implemented on a per-spell basis?

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
Nothing has changed since then. Although bots are valid targets for player-only abilities (players have to use `.npcb use` command to circumvent client-side restrictions), boss abilities set to search for player target(s) explicitly have to be carefully checked if they can be applied to bots safely.
