### ISSUE TITLE
Black Rock Depths crashes server

### ISSUE THREAD

**Issue by skipperheart** [trickerer/Trinity-Bots#96]
Black Rock Depths crashes the server after the boss at the Pit. Come out into the new room and the server crashes. It reports that the maps are missing, so i will need to test without bots.

**Comment by Mr-Deadbeat** [comment]
if you get maps missing errors it might be due to Trinitycore recently updated the tools for extracting the maps which is mandatory to do again i think the commit on their site mentioned this

although have not tested BRD in quite a while now
but are you referring to the "The Ring of Law" by any chance ? i might sneak in there to see if it happens to me as well if it crashes there you need to create an issue with the TC devs trickerer only supply the bots ;)

but most likely the issue has to do with the tools being updated and you have not extracted the maps again

**Comment by skipperheart** [comment]
I just tried this again after a server reboot.
Solo is fine.
With one Bot is fine. 

I need to check with a full group, but maybe the server just wanted a restart.

The maps have recently been pulled although its not the latest revision (i know my next update will require new maps). That's why i was putting off the update. I'm only using a Celeron based CPU so it takes a while :)

**Comment by skipperheart** [comment]
This can be closed. Seems to have been a server issue.
